// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/payment/ent/payment"
	"lab2/payment/ent/predicate"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPaymentUID sets the "payment_uid" field.
func (_u *PaymentUpdate) SetPaymentUID(v uuid.UUID) *PaymentUpdate {
	_u.mutation.SetPaymentUID(v)
	return _u
}

// SetNillablePaymentUID sets the "payment_uid" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePaymentUID(v *uuid.UUID) *PaymentUpdate {
	if v != nil {
		_u.SetPaymentUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v payment.Status) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *payment.Status) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *PaymentUpdate) SetPrice(v int) *PaymentUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePrice(v *int) *PaymentUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PaymentUpdate) AddPrice(v int) *PaymentUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentUID(); ok {
		vv, err := payment.ValueScanner.PaymentUID.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(payment.FieldPaymentUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(payment.FieldPrice, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetPaymentUID sets the "payment_uid" field.
func (_u *PaymentUpdateOne) SetPaymentUID(v uuid.UUID) *PaymentUpdateOne {
	_u.mutation.SetPaymentUID(v)
	return _u
}

// SetNillablePaymentUID sets the "payment_uid" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePaymentUID(v *uuid.UUID) *PaymentUpdateOne {
	if v != nil {
		_u.SetPaymentUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v payment.Status) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *payment.Status) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *PaymentUpdateOne) SetPrice(v int) *PaymentUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePrice(v *int) *PaymentUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PaymentUpdateOne) AddPrice(v int) *PaymentUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentUID(); ok {
		vv, err := payment.ValueScanner.PaymentUID.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(payment.FieldPaymentUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(payment.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(payment.FieldPrice, field.TypeInt, value)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
