// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lab2/payment/ent/payment"
	"lab2/payment/ent/schema"
	"uuid"

	"entgo.io/ent/schema/field"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescPaymentUID is the schema descriptor for payment_uid field.
	paymentDescPaymentUID := paymentFields[0].Descriptor()
	payment.ValueScanner.PaymentUID = paymentDescPaymentUID.ValueScanner.(field.TypeValueScanner[uuid.UUID])
}
