// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentColumns holds the columns for the "payment" table.
	PaymentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "payment_uid", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PAID", "CANCELED"}},
		{Name: "price", Type: field.TypeInt},
	}
	// PaymentTable holds the schema information for the "payment" table.
	PaymentTable = &schema.Table{
		Name:       "payment",
		Columns:    PaymentColumns,
		PrimaryKey: []*schema.Column{PaymentColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "payment_payment_uid",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentTable,
	}
)

func init() {
	PaymentTable.Annotation = &entsql.Annotation{
		Table: "payment",
	}
}
