// Code generated by ent, DO NOT EDIT.

package hotel

import (
	"fmt"
	"lab2/reservation/ent/predicate"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldID, id))
}

// HotelUID applies equality check predicate on the "hotel_uid" field. It's identical to HotelUIDEQ.
func HotelUID(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldEQ(FieldHotelUID, vc), err)
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldName, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCountry, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCity, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldAddress, v))
}

// Stars applies equality check predicate on the "stars" field. It's identical to StarsEQ.
func Stars(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldStars, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPrice, v))
}

// HotelUIDEQ applies the EQ predicate on the "hotel_uid" field.
func HotelUIDEQ(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldEQ(FieldHotelUID, vc), err)
}

// HotelUIDNEQ applies the NEQ predicate on the "hotel_uid" field.
func HotelUIDNEQ(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldNEQ(FieldHotelUID, vc), err)
}

// HotelUIDIn applies the In predicate on the "hotel_uid" field.
func HotelUIDIn(vs ...uuid.UUID) predicate.Hotel {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.HotelUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.HotelOrErr(sql.FieldIn(FieldHotelUID, v...), err)
}

// HotelUIDNotIn applies the NotIn predicate on the "hotel_uid" field.
func HotelUIDNotIn(vs ...uuid.UUID) predicate.Hotel {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.HotelUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.HotelOrErr(sql.FieldNotIn(FieldHotelUID, v...), err)
}

// HotelUIDGT applies the GT predicate on the "hotel_uid" field.
func HotelUIDGT(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldGT(FieldHotelUID, vc), err)
}

// HotelUIDGTE applies the GTE predicate on the "hotel_uid" field.
func HotelUIDGTE(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldGTE(FieldHotelUID, vc), err)
}

// HotelUIDLT applies the LT predicate on the "hotel_uid" field.
func HotelUIDLT(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldLT(FieldHotelUID, vc), err)
}

// HotelUIDLTE applies the LTE predicate on the "hotel_uid" field.
func HotelUIDLTE(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	return predicate.HotelOrErr(sql.FieldLTE(FieldHotelUID, vc), err)
}

// HotelUIDContains applies the Contains predicate on the "hotel_uid" field.
func HotelUIDContains(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("hotel_uid value is not a string: %T", vc)
	}
	return predicate.HotelOrErr(sql.FieldContains(FieldHotelUID, vcs), err)
}

// HotelUIDHasPrefix applies the HasPrefix predicate on the "hotel_uid" field.
func HotelUIDHasPrefix(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("hotel_uid value is not a string: %T", vc)
	}
	return predicate.HotelOrErr(sql.FieldHasPrefix(FieldHotelUID, vcs), err)
}

// HotelUIDHasSuffix applies the HasSuffix predicate on the "hotel_uid" field.
func HotelUIDHasSuffix(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("hotel_uid value is not a string: %T", vc)
	}
	return predicate.HotelOrErr(sql.FieldHasSuffix(FieldHotelUID, vcs), err)
}

// HotelUIDEqualFold applies the EqualFold predicate on the "hotel_uid" field.
func HotelUIDEqualFold(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("hotel_uid value is not a string: %T", vc)
	}
	return predicate.HotelOrErr(sql.FieldEqualFold(FieldHotelUID, vcs), err)
}

// HotelUIDContainsFold applies the ContainsFold predicate on the "hotel_uid" field.
func HotelUIDContainsFold(v uuid.UUID) predicate.Hotel {
	vc, err := ValueScanner.HotelUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("hotel_uid value is not a string: %T", vc)
	}
	return predicate.HotelOrErr(sql.FieldContainsFold(FieldHotelUID, vcs), err)
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldName, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldCountry, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldCity, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Hotel {
	return predicate.Hotel(sql.FieldContainsFold(FieldAddress, v))
}

// StarsEQ applies the EQ predicate on the "stars" field.
func StarsEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldStars, v))
}

// StarsNEQ applies the NEQ predicate on the "stars" field.
func StarsNEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldStars, v))
}

// StarsIn applies the In predicate on the "stars" field.
func StarsIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldStars, vs...))
}

// StarsNotIn applies the NotIn predicate on the "stars" field.
func StarsNotIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldStars, vs...))
}

// StarsGT applies the GT predicate on the "stars" field.
func StarsGT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldStars, v))
}

// StarsGTE applies the GTE predicate on the "stars" field.
func StarsGTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldStars, v))
}

// StarsLT applies the LT predicate on the "stars" field.
func StarsLT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldStars, v))
}

// StarsLTE applies the LTE predicate on the "stars" field.
func StarsLTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldStars, v))
}

// StarsIsNil applies the IsNil predicate on the "stars" field.
func StarsIsNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldIsNull(FieldStars))
}

// StarsNotNil applies the NotNil predicate on the "stars" field.
func StarsNotNil() predicate.Hotel {
	return predicate.Hotel(sql.FieldNotNull(FieldStars))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int) predicate.Hotel {
	return predicate.Hotel(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int) predicate.Hotel {
	return predicate.Hotel(sql.FieldLTE(FieldPrice, v))
}

// HasReservations applies the HasEdge predicate on the "reservations" edge.
func HasReservations() predicate.Hotel {
	return predicate.Hotel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReservationsTable, ReservationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReservationsWith applies the HasEdge predicate on the "reservations" edge with a given conditions (other predicates).
func HasReservationsWith(preds ...predicate.Reservation) predicate.Hotel {
	return predicate.Hotel(func(s *sql.Selector) {
		step := newReservationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hotel) predicate.Hotel {
	return predicate.Hotel(sql.NotPredicates(p))
}
