// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HotelsColumns holds the columns for the "hotels" table.
	HotelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hotel_uid", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "country", Type: field.TypeString, Size: 80},
		{Name: "city", Type: field.TypeString, Size: 80},
		{Name: "address", Type: field.TypeString, Size: 255},
		{Name: "stars", Type: field.TypeInt, Nullable: true},
		{Name: "price", Type: field.TypeInt},
	}
	// HotelsTable holds the schema information for the "hotels" table.
	HotelsTable = &schema.Table{
		Name:       "hotels",
		Columns:    HotelsColumns,
		PrimaryKey: []*schema.Column{HotelsColumns[0]},
	}
	// ReservationColumns holds the columns for the "reservation" table.
	ReservationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "reservation_uid", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "username", Type: field.TypeString, Size: 80},
		{Name: "payment_uid", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PAID", "CANCELED"}},
		{Name: "start_date", Type: field.TypeTime, Nullable: true},
		{Name: "end_data", Type: field.TypeTime, Nullable: true},
		{Name: "hotel_id", Type: field.TypeInt, Nullable: true},
	}
	// ReservationTable holds the schema information for the "reservation" table.
	ReservationTable = &schema.Table{
		Name:       "reservation",
		Columns:    ReservationColumns,
		PrimaryKey: []*schema.Column{ReservationColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reservation_hotels_reservations",
				Columns:    []*schema.Column{ReservationColumns[7]},
				RefColumns: []*schema.Column{HotelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "reservation_username",
				Unique:  false,
				Columns: []*schema.Column{ReservationColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HotelsTable,
		ReservationTable,
	}
)

func init() {
	HotelsTable.Annotation = &entsql.Annotation{
		Table: "hotels",
	}
	ReservationTable.ForeignKeys[0].RefTable = HotelsTable
	ReservationTable.Annotation = &entsql.Annotation{
		Table: "reservation",
	}
}
