// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hotel is the predicate function for hotel builders.
type Hotel func(*sql.Selector)

// HotelOrErr calls the predicate only if the error is not nit.
func HotelOrErr(p Hotel, err error) Hotel {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// ReservationOrErr calls the predicate only if the error is not nit.
func ReservationOrErr(p Reservation, err error) Reservation {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
