// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/predicate"
	"lab2/reservation/ent/reservation"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotelUpdate is the builder for updating Hotel entities.
type HotelUpdate struct {
	config
	hooks    []Hook
	mutation *HotelMutation
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdate) Where(ps ...predicate.Hotel) *HotelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHotelUID sets the "hotel_uid" field.
func (_u *HotelUpdate) SetHotelUID(v uuid.UUID) *HotelUpdate {
	_u.mutation.SetHotelUID(v)
	return _u
}

// SetNillableHotelUID sets the "hotel_uid" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableHotelUID(v *uuid.UUID) *HotelUpdate {
	if v != nil {
		_u.SetHotelUID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HotelUpdate) SetName(v string) *HotelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableName(v *string) *HotelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *HotelUpdate) SetCountry(v string) *HotelUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableCountry(v *string) *HotelUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *HotelUpdate) SetCity(v string) *HotelUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableCity(v *string) *HotelUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *HotelUpdate) SetAddress(v string) *HotelUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableAddress(v *string) *HotelUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetStars sets the "stars" field.
func (_u *HotelUpdate) SetStars(v int) *HotelUpdate {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *HotelUpdate) SetNillableStars(v *int) *HotelUpdate {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *HotelUpdate) AddStars(v int) *HotelUpdate {
	_u.mutation.AddStars(v)
	return _u
}

// ClearStars clears the value of the "stars" field.
func (_u *HotelUpdate) ClearStars() *HotelUpdate {
	_u.mutation.ClearStars()
	return _u
}

// SetPrice sets the "price" field.
func (_u *HotelUpdate) SetPrice(v int) *HotelUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *HotelUpdate) SetNillablePrice(v *int) *HotelUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *HotelUpdate) AddPrice(v int) *HotelUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// AddReservationIDs adds the "reservations" edge to the Reservation entity by IDs.
func (_u *HotelUpdate) AddReservationIDs(ids ...int) *HotelUpdate {
	_u.mutation.AddReservationIDs(ids...)
	return _u
}

// AddReservations adds the "reservations" edges to the Reservation entity.
func (_u *HotelUpdate) AddReservations(v ...*Reservation) *HotelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReservationIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdate) Mutation() *HotelMutation {
	return _u.mutation
}

// ClearReservations clears all "reservations" edges to the Reservation entity.
func (_u *HotelUpdate) ClearReservations() *HotelUpdate {
	_u.mutation.ClearReservations()
	return _u
}

// RemoveReservationIDs removes the "reservations" edge to Reservation entities by IDs.
func (_u *HotelUpdate) RemoveReservationIDs(ids ...int) *HotelUpdate {
	_u.mutation.RemoveReservationIDs(ids...)
	return _u
}

// RemoveReservations removes "reservations" edges to Reservation entities.
func (_u *HotelUpdate) RemoveReservations(v ...*Reservation) *HotelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReservationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HotelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HotelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := hotel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hotel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := hotel.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Hotel.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := hotel.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Hotel.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := hotel.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Hotel.address": %w`, err)}
		}
	}
	return nil
}

func (_u *HotelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HotelUID(); ok {
		vv, err := hotel.ValueScanner.HotelUID.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(hotel.FieldHotelUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(hotel.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(hotel.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(hotel.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(hotel.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(hotel.FieldStars, field.TypeInt, value)
	}
	if _u.mutation.StarsCleared() {
		_spec.ClearField(hotel.FieldStars, field.TypeInt)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(hotel.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(hotel.FieldPrice, field.TypeInt, value)
	}
	if _u.mutation.ReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReservationsIDs(); len(nodes) > 0 && !_u.mutation.ReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HotelUpdateOne is the builder for updating a single Hotel entity.
type HotelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HotelMutation
}

// SetHotelUID sets the "hotel_uid" field.
func (_u *HotelUpdateOne) SetHotelUID(v uuid.UUID) *HotelUpdateOne {
	_u.mutation.SetHotelUID(v)
	return _u
}

// SetNillableHotelUID sets the "hotel_uid" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableHotelUID(v *uuid.UUID) *HotelUpdateOne {
	if v != nil {
		_u.SetHotelUID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *HotelUpdateOne) SetName(v string) *HotelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableName(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *HotelUpdateOne) SetCountry(v string) *HotelUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableCountry(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *HotelUpdateOne) SetCity(v string) *HotelUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableCity(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *HotelUpdateOne) SetAddress(v string) *HotelUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableAddress(v *string) *HotelUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetStars sets the "stars" field.
func (_u *HotelUpdateOne) SetStars(v int) *HotelUpdateOne {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillableStars(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *HotelUpdateOne) AddStars(v int) *HotelUpdateOne {
	_u.mutation.AddStars(v)
	return _u
}

// ClearStars clears the value of the "stars" field.
func (_u *HotelUpdateOne) ClearStars() *HotelUpdateOne {
	_u.mutation.ClearStars()
	return _u
}

// SetPrice sets the "price" field.
func (_u *HotelUpdateOne) SetPrice(v int) *HotelUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *HotelUpdateOne) SetNillablePrice(v *int) *HotelUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *HotelUpdateOne) AddPrice(v int) *HotelUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// AddReservationIDs adds the "reservations" edge to the Reservation entity by IDs.
func (_u *HotelUpdateOne) AddReservationIDs(ids ...int) *HotelUpdateOne {
	_u.mutation.AddReservationIDs(ids...)
	return _u
}

// AddReservations adds the "reservations" edges to the Reservation entity.
func (_u *HotelUpdateOne) AddReservations(v ...*Reservation) *HotelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReservationIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_u *HotelUpdateOne) Mutation() *HotelMutation {
	return _u.mutation
}

// ClearReservations clears all "reservations" edges to the Reservation entity.
func (_u *HotelUpdateOne) ClearReservations() *HotelUpdateOne {
	_u.mutation.ClearReservations()
	return _u
}

// RemoveReservationIDs removes the "reservations" edge to Reservation entities by IDs.
func (_u *HotelUpdateOne) RemoveReservationIDs(ids ...int) *HotelUpdateOne {
	_u.mutation.RemoveReservationIDs(ids...)
	return _u
}

// RemoveReservations removes "reservations" edges to Reservation entities.
func (_u *HotelUpdateOne) RemoveReservations(v ...*Reservation) *HotelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReservationIDs(ids...)
}

// Where appends a list predicates to the HotelUpdate builder.
func (_u *HotelUpdateOne) Where(ps ...predicate.Hotel) *HotelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HotelUpdateOne) Select(field string, fields ...string) *HotelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Hotel entity.
func (_u *HotelUpdateOne) Save(ctx context.Context) (*Hotel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HotelUpdateOne) SaveX(ctx context.Context) *Hotel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HotelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HotelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HotelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := hotel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hotel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := hotel.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Hotel.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := hotel.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Hotel.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := hotel.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Hotel.address": %w`, err)}
		}
	}
	return nil
}

func (_u *HotelUpdateOne) sqlSave(ctx context.Context) (_node *Hotel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hotel.Table, hotel.Columns, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hotel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hotel.FieldID)
		for _, f := range fields {
			if !hotel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hotel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.HotelUID(); ok {
		vv, err := hotel.ValueScanner.HotelUID.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(hotel.FieldHotelUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(hotel.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(hotel.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(hotel.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(hotel.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(hotel.FieldStars, field.TypeInt, value)
	}
	if _u.mutation.StarsCleared() {
		_spec.ClearField(hotel.FieldStars, field.TypeInt)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(hotel.FieldPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(hotel.FieldPrice, field.TypeInt, value)
	}
	if _u.mutation.ReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReservationsIDs(); len(nodes) > 0 && !_u.mutation.ReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hotel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hotel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
