// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/reservation"
	"uuid"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HotelCreate is the builder for creating a Hotel entity.
type HotelCreate struct {
	config
	mutation *HotelMutation
	hooks    []Hook
}

// SetHotelUID sets the "hotel_uid" field.
func (_c *HotelCreate) SetHotelUID(v uuid.UUID) *HotelCreate {
	_c.mutation.SetHotelUID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *HotelCreate) SetName(v string) *HotelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *HotelCreate) SetCountry(v string) *HotelCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *HotelCreate) SetCity(v string) *HotelCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *HotelCreate) SetAddress(v string) *HotelCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetStars sets the "stars" field.
func (_c *HotelCreate) SetStars(v int) *HotelCreate {
	_c.mutation.SetStars(v)
	return _c
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_c *HotelCreate) SetNillableStars(v *int) *HotelCreate {
	if v != nil {
		_c.SetStars(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *HotelCreate) SetPrice(v int) *HotelCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// AddReservationIDs adds the "reservations" edge to the Reservation entity by IDs.
func (_c *HotelCreate) AddReservationIDs(ids ...int) *HotelCreate {
	_c.mutation.AddReservationIDs(ids...)
	return _c
}

// AddReservations adds the "reservations" edges to the Reservation entity.
func (_c *HotelCreate) AddReservations(v ...*Reservation) *HotelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReservationIDs(ids...)
}

// Mutation returns the HotelMutation object of the builder.
func (_c *HotelCreate) Mutation() *HotelMutation {
	return _c.mutation
}

// Save creates the Hotel in the database.
func (_c *HotelCreate) Save(ctx context.Context) (*Hotel, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HotelCreate) SaveX(ctx context.Context) *Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HotelCreate) check() error {
	if _, ok := _c.mutation.HotelUID(); !ok {
		return &ValidationError{Name: "hotel_uid", err: errors.New(`ent: missing required field "Hotel.hotel_uid"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Hotel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := hotel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hotel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Hotel.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := hotel.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Hotel.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Hotel.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := hotel.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Hotel.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Hotel.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := hotel.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Hotel.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Hotel.price"`)}
	}
	return nil
}

func (_c *HotelCreate) sqlSave(ctx context.Context) (*Hotel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HotelCreate) createSpec() (*Hotel, *sqlgraph.CreateSpec, error) {
	var (
		_node = &Hotel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hotel.Table, sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.HotelUID(); ok {
		vv, err := hotel.ValueScanner.HotelUID.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(hotel.FieldHotelUID, field.TypeString, vv)
		_node.HotelUID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(hotel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(hotel.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(hotel.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(hotel.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Stars(); ok {
		_spec.SetField(hotel.FieldStars, field.TypeInt, value)
		_node.Stars = &value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(hotel.FieldPrice, field.TypeInt, value)
		_node.Price = value
	}
	if nodes := _c.mutation.ReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hotel.ReservationsTable,
			Columns: []string{hotel.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// HotelCreateBulk is the builder for creating many Hotel entities in bulk.
type HotelCreateBulk struct {
	config
	err      error
	builders []*HotelCreate
}

// Save creates the Hotel entities in the database.
func (_c *HotelCreateBulk) Save(ctx context.Context) ([]*Hotel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Hotel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HotelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HotelCreateBulk) SaveX(ctx context.Context) []*Hotel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HotelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HotelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
