// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/predicate"
	"lab2/reservation/ent/reservation"
	"sync"
	"time"
	"uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHotel       = "Hotel"
	TypeReservation = "Reservation"
)

// HotelMutation represents an operation that mutates the Hotel nodes in the graph.
type HotelMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	hotel_uid           *uuid.UUID
	name                *string
	country             *string
	city                *string
	address             *string
	stars               *int
	addstars            *int
	price               *int
	addprice            *int
	clearedFields       map[string]struct{}
	reservations        map[int]struct{}
	removedreservations map[int]struct{}
	clearedreservations bool
	done                bool
	oldValue            func(context.Context) (*Hotel, error)
	predicates          []predicate.Hotel
}

var _ ent.Mutation = (*HotelMutation)(nil)

// hotelOption allows management of the mutation configuration using functional options.
type hotelOption func(*HotelMutation)

// newHotelMutation creates new mutation for the Hotel entity.
func newHotelMutation(c config, op Op, opts ...hotelOption) *HotelMutation {
	m := &HotelMutation{
		config:        c,
		op:            op,
		typ:           TypeHotel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHotelID sets the ID field of the mutation.
func withHotelID(id int) hotelOption {
	return func(m *HotelMutation) {
		var (
			err   error
			once  sync.Once
			value *Hotel
		)
		m.oldValue = func(ctx context.Context) (*Hotel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Hotel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHotel sets the old Hotel of the mutation.
func withHotel(node *Hotel) hotelOption {
	return func(m *HotelMutation) {
		m.oldValue = func(context.Context) (*Hotel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HotelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HotelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HotelMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HotelMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Hotel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHotelUID sets the "hotel_uid" field.
func (m *HotelMutation) SetHotelUID(u uuid.UUID) {
	m.hotel_uid = &u
}

// HotelUID returns the value of the "hotel_uid" field in the mutation.
func (m *HotelMutation) HotelUID() (r uuid.UUID, exists bool) {
	v := m.hotel_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldHotelUID returns the old "hotel_uid" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldHotelUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHotelUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHotelUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHotelUID: %w", err)
	}
	return oldValue.HotelUID, nil
}

// ResetHotelUID resets all changes to the "hotel_uid" field.
func (m *HotelMutation) ResetHotelUID() {
	m.hotel_uid = nil
}

// SetName sets the "name" field.
func (m *HotelMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *HotelMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *HotelMutation) ResetName() {
	m.name = nil
}

// SetCountry sets the "country" field.
func (m *HotelMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *HotelMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ResetCountry resets all changes to the "country" field.
func (m *HotelMutation) ResetCountry() {
	m.country = nil
}

// SetCity sets the "city" field.
func (m *HotelMutation) SetCity(s string) {
	m.city = &s
}

// City returns the value of the "city" field in the mutation.
func (m *HotelMutation) City() (r string, exists bool) {
	v := m.city
	if v == nil {
		return
	}
	return *v, true
}

// OldCity returns the old "city" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldCity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCity: %w", err)
	}
	return oldValue.City, nil
}

// ResetCity resets all changes to the "city" field.
func (m *HotelMutation) ResetCity() {
	m.city = nil
}

// SetAddress sets the "address" field.
func (m *HotelMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *HotelMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *HotelMutation) ResetAddress() {
	m.address = nil
}

// SetStars sets the "stars" field.
func (m *HotelMutation) SetStars(i int) {
	m.stars = &i
	m.addstars = nil
}

// Stars returns the value of the "stars" field in the mutation.
func (m *HotelMutation) Stars() (r int, exists bool) {
	v := m.stars
	if v == nil {
		return
	}
	return *v, true
}

// OldStars returns the old "stars" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldStars(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStars is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStars requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStars: %w", err)
	}
	return oldValue.Stars, nil
}

// AddStars adds i to the "stars" field.
func (m *HotelMutation) AddStars(i int) {
	if m.addstars != nil {
		*m.addstars += i
	} else {
		m.addstars = &i
	}
}

// AddedStars returns the value that was added to the "stars" field in this mutation.
func (m *HotelMutation) AddedStars() (r int, exists bool) {
	v := m.addstars
	if v == nil {
		return
	}
	return *v, true
}

// ClearStars clears the value of the "stars" field.
func (m *HotelMutation) ClearStars() {
	m.stars = nil
	m.addstars = nil
	m.clearedFields[hotel.FieldStars] = struct{}{}
}

// StarsCleared returns if the "stars" field was cleared in this mutation.
func (m *HotelMutation) StarsCleared() bool {
	_, ok := m.clearedFields[hotel.FieldStars]
	return ok
}

// ResetStars resets all changes to the "stars" field.
func (m *HotelMutation) ResetStars() {
	m.stars = nil
	m.addstars = nil
	delete(m.clearedFields, hotel.FieldStars)
}

// SetPrice sets the "price" field.
func (m *HotelMutation) SetPrice(i int) {
	m.price = &i
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *HotelMutation) Price() (r int, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the Hotel entity.
// If the Hotel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HotelMutation) OldPrice(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds i to the "price" field.
func (m *HotelMutation) AddPrice(i int) {
	if m.addprice != nil {
		*m.addprice += i
	} else {
		m.addprice = &i
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *HotelMutation) AddedPrice() (r int, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *HotelMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// AddReservationIDs adds the "reservations" edge to the Reservation entity by ids.
func (m *HotelMutation) AddReservationIDs(ids ...int) {
	if m.reservations == nil {
		m.reservations = make(map[int]struct{})
	}
	for i := range ids {
		m.reservations[ids[i]] = struct{}{}
	}
}

// ClearReservations clears the "reservations" edge to the Reservation entity.
func (m *HotelMutation) ClearReservations() {
	m.clearedreservations = true
}

// ReservationsCleared reports if the "reservations" edge to the Reservation entity was cleared.
func (m *HotelMutation) ReservationsCleared() bool {
	return m.clearedreservations
}

// RemoveReservationIDs removes the "reservations" edge to the Reservation entity by IDs.
func (m *HotelMutation) RemoveReservationIDs(ids ...int) {
	if m.removedreservations == nil {
		m.removedreservations = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.reservations, ids[i])
		m.removedreservations[ids[i]] = struct{}{}
	}
}

// RemovedReservations returns the removed IDs of the "reservations" edge to the Reservation entity.
func (m *HotelMutation) RemovedReservationsIDs() (ids []int) {
	for id := range m.removedreservations {
		ids = append(ids, id)
	}
	return
}

// ReservationsIDs returns the "reservations" edge IDs in the mutation.
func (m *HotelMutation) ReservationsIDs() (ids []int) {
	for id := range m.reservations {
		ids = append(ids, id)
	}
	return
}

// ResetReservations resets all changes to the "reservations" edge.
func (m *HotelMutation) ResetReservations() {
	m.reservations = nil
	m.clearedreservations = false
	m.removedreservations = nil
}

// Where appends a list predicates to the HotelMutation builder.
func (m *HotelMutation) Where(ps ...predicate.Hotel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HotelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HotelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Hotel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HotelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HotelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Hotel).
func (m *HotelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HotelMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.hotel_uid != nil {
		fields = append(fields, hotel.FieldHotelUID)
	}
	if m.name != nil {
		fields = append(fields, hotel.FieldName)
	}
	if m.country != nil {
		fields = append(fields, hotel.FieldCountry)
	}
	if m.city != nil {
		fields = append(fields, hotel.FieldCity)
	}
	if m.address != nil {
		fields = append(fields, hotel.FieldAddress)
	}
	if m.stars != nil {
		fields = append(fields, hotel.FieldStars)
	}
	if m.price != nil {
		fields = append(fields, hotel.FieldPrice)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HotelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldHotelUID:
		return m.HotelUID()
	case hotel.FieldName:
		return m.Name()
	case hotel.FieldCountry:
		return m.Country()
	case hotel.FieldCity:
		return m.City()
	case hotel.FieldAddress:
		return m.Address()
	case hotel.FieldStars:
		return m.Stars()
	case hotel.FieldPrice:
		return m.Price()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HotelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case hotel.FieldHotelUID:
		return m.OldHotelUID(ctx)
	case hotel.FieldName:
		return m.OldName(ctx)
	case hotel.FieldCountry:
		return m.OldCountry(ctx)
	case hotel.FieldCity:
		return m.OldCity(ctx)
	case hotel.FieldAddress:
		return m.OldAddress(ctx)
	case hotel.FieldStars:
		return m.OldStars(ctx)
	case hotel.FieldPrice:
		return m.OldPrice(ctx)
	}
	return nil, fmt.Errorf("unknown Hotel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldHotelUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHotelUID(v)
		return nil
	case hotel.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case hotel.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	case hotel.FieldCity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCity(v)
		return nil
	case hotel.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case hotel.FieldStars:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStars(v)
		return nil
	case hotel.FieldPrice:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HotelMutation) AddedFields() []string {
	var fields []string
	if m.addstars != nil {
		fields = append(fields, hotel.FieldStars)
	}
	if m.addprice != nil {
		fields = append(fields, hotel.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HotelMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case hotel.FieldStars:
		return m.AddedStars()
	case hotel.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HotelMutation) AddField(name string, value ent.Value) error {
	switch name {
	case hotel.FieldStars:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStars(v)
		return nil
	case hotel.FieldPrice:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown Hotel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HotelMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(hotel.FieldStars) {
		fields = append(fields, hotel.FieldStars)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HotelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HotelMutation) ClearField(name string) error {
	switch name {
	case hotel.FieldStars:
		m.ClearStars()
		return nil
	}
	return fmt.Errorf("unknown Hotel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HotelMutation) ResetField(name string) error {
	switch name {
	case hotel.FieldHotelUID:
		m.ResetHotelUID()
		return nil
	case hotel.FieldName:
		m.ResetName()
		return nil
	case hotel.FieldCountry:
		m.ResetCountry()
		return nil
	case hotel.FieldCity:
		m.ResetCity()
		return nil
	case hotel.FieldAddress:
		m.ResetAddress()
		return nil
	case hotel.FieldStars:
		m.ResetStars()
		return nil
	case hotel.FieldPrice:
		m.ResetPrice()
		return nil
	}
	return fmt.Errorf("unknown Hotel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HotelMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.reservations != nil {
		edges = append(edges, hotel.EdgeReservations)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HotelMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case hotel.EdgeReservations:
		ids := make([]ent.Value, 0, len(m.reservations))
		for id := range m.reservations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HotelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedreservations != nil {
		edges = append(edges, hotel.EdgeReservations)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HotelMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case hotel.EdgeReservations:
		ids := make([]ent.Value, 0, len(m.removedreservations))
		for id := range m.removedreservations {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HotelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedreservations {
		edges = append(edges, hotel.EdgeReservations)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HotelMutation) EdgeCleared(name string) bool {
	switch name {
	case hotel.EdgeReservations:
		return m.clearedreservations
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HotelMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Hotel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HotelMutation) ResetEdge(name string) error {
	switch name {
	case hotel.EdgeReservations:
		m.ResetReservations()
		return nil
	}
	return fmt.Errorf("unknown Hotel edge %s", name)
}

// ReservationMutation represents an operation that mutates the Reservation nodes in the graph.
type ReservationMutation struct {
	config
	op              Op
	typ             string
	id              *int
	reservation_uid *uuid.UUID
	username        *string
	payment_uid     *uuid.UUID
	status          *reservation.Status
	start_date      *time.Time
	end_date        *time.Time
	clearedFields   map[string]struct{}
	hotel           *int
	clearedhotel    bool
	done            bool
	oldValue        func(context.Context) (*Reservation, error)
	predicates      []predicate.Reservation
}

var _ ent.Mutation = (*ReservationMutation)(nil)

// reservationOption allows management of the mutation configuration using functional options.
type reservationOption func(*ReservationMutation)

// newReservationMutation creates new mutation for the Reservation entity.
func newReservationMutation(c config, op Op, opts ...reservationOption) *ReservationMutation {
	m := &ReservationMutation{
		config:        c,
		op:            op,
		typ:           TypeReservation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withReservationID sets the ID field of the mutation.
func withReservationID(id int) reservationOption {
	return func(m *ReservationMutation) {
		var (
			err   error
			once  sync.Once
			value *Reservation
		)
		m.oldValue = func(ctx context.Context) (*Reservation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Reservation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withReservation sets the old Reservation of the mutation.
func withReservation(node *Reservation) reservationOption {
	return func(m *ReservationMutation) {
		m.oldValue = func(context.Context) (*Reservation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ReservationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ReservationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ReservationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ReservationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Reservation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetReservationUID sets the "reservation_uid" field.
func (m *ReservationMutation) SetReservationUID(u uuid.UUID) {
	m.reservation_uid = &u
}

// ReservationUID returns the value of the "reservation_uid" field in the mutation.
func (m *ReservationMutation) ReservationUID() (r uuid.UUID, exists bool) {
	v := m.reservation_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldReservationUID returns the old "reservation_uid" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldReservationUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReservationUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReservationUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReservationUID: %w", err)
	}
	return oldValue.ReservationUID, nil
}

// ResetReservationUID resets all changes to the "reservation_uid" field.
func (m *ReservationMutation) ResetReservationUID() {
	m.reservation_uid = nil
}

// SetUsername sets the "username" field.
func (m *ReservationMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *ReservationMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *ReservationMutation) ResetUsername() {
	m.username = nil
}

// SetPaymentUID sets the "payment_uid" field.
func (m *ReservationMutation) SetPaymentUID(u uuid.UUID) {
	m.payment_uid = &u
}

// PaymentUID returns the value of the "payment_uid" field in the mutation.
func (m *ReservationMutation) PaymentUID() (r uuid.UUID, exists bool) {
	v := m.payment_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldPaymentUID returns the old "payment_uid" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldPaymentUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPaymentUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPaymentUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPaymentUID: %w", err)
	}
	return oldValue.PaymentUID, nil
}

// ResetPaymentUID resets all changes to the "payment_uid" field.
func (m *ReservationMutation) ResetPaymentUID() {
	m.payment_uid = nil
}

// SetHotelID sets the "hotel_id" field.
func (m *ReservationMutation) SetHotelID(i int) {
	m.hotel = &i
}

// HotelID returns the value of the "hotel_id" field in the mutation.
func (m *ReservationMutation) HotelID() (r int, exists bool) {
	v := m.hotel
	if v == nil {
		return
	}
	return *v, true
}

// OldHotelID returns the old "hotel_id" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldHotelID(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHotelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHotelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHotelID: %w", err)
	}
	return oldValue.HotelID, nil
}

// ClearHotelID clears the value of the "hotel_id" field.
func (m *ReservationMutation) ClearHotelID() {
	m.hotel = nil
	m.clearedFields[reservation.FieldHotelID] = struct{}{}
}

// HotelIDCleared returns if the "hotel_id" field was cleared in this mutation.
func (m *ReservationMutation) HotelIDCleared() bool {
	_, ok := m.clearedFields[reservation.FieldHotelID]
	return ok
}

// ResetHotelID resets all changes to the "hotel_id" field.
func (m *ReservationMutation) ResetHotelID() {
	m.hotel = nil
	delete(m.clearedFields, reservation.FieldHotelID)
}

// SetStatus sets the "status" field.
func (m *ReservationMutation) SetStatus(r reservation.Status) {
	m.status = &r
}

// Status returns the value of the "status" field in the mutation.
func (m *ReservationMutation) Status() (r reservation.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldStatus(ctx context.Context) (v reservation.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ReservationMutation) ResetStatus() {
	m.status = nil
}

// SetStartDate sets the "start_date" field.
func (m *ReservationMutation) SetStartDate(t time.Time) {
	m.start_date = &t
}

// StartDate returns the value of the "start_date" field in the mutation.
func (m *ReservationMutation) StartDate() (r time.Time, exists bool) {
	v := m.start_date
	if v == nil {
		return
	}
	return *v, true
}

// OldStartDate returns the old "start_date" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldStartDate(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartDate: %w", err)
	}
	return oldValue.StartDate, nil
}

// ClearStartDate clears the value of the "start_date" field.
func (m *ReservationMutation) ClearStartDate() {
	m.start_date = nil
	m.clearedFields[reservation.FieldStartDate] = struct{}{}
}

// StartDateCleared returns if the "start_date" field was cleared in this mutation.
func (m *ReservationMutation) StartDateCleared() bool {
	_, ok := m.clearedFields[reservation.FieldStartDate]
	return ok
}

// ResetStartDate resets all changes to the "start_date" field.
func (m *ReservationMutation) ResetStartDate() {
	m.start_date = nil
	delete(m.clearedFields, reservation.FieldStartDate)
}

// SetEndDate sets the "end_date" field.
func (m *ReservationMutation) SetEndDate(t time.Time) {
	m.end_date = &t
}

// EndDate returns the value of the "end_date" field in the mutation.
func (m *ReservationMutation) EndDate() (r time.Time, exists bool) {
	v := m.end_date
	if v == nil {
		return
	}
	return *v, true
}

// OldEndDate returns the old "end_date" field's value of the Reservation entity.
// If the Reservation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReservationMutation) OldEndDate(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEndDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEndDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndDate: %w", err)
	}
	return oldValue.EndDate, nil
}

// ClearEndDate clears the value of the "end_date" field.
func (m *ReservationMutation) ClearEndDate() {
	m.end_date = nil
	m.clearedFields[reservation.FieldEndDate] = struct{}{}
}

// EndDateCleared returns if the "end_date" field was cleared in this mutation.
func (m *ReservationMutation) EndDateCleared() bool {
	_, ok := m.clearedFields[reservation.FieldEndDate]
	return ok
}

// ResetEndDate resets all changes to the "end_date" field.
func (m *ReservationMutation) ResetEndDate() {
	m.end_date = nil
	delete(m.clearedFields, reservation.FieldEndDate)
}

// ClearHotel clears the "hotel" edge to the Hotel entity.
func (m *ReservationMutation) ClearHotel() {
	m.clearedhotel = true
	m.clearedFields[reservation.FieldHotelID] = struct{}{}
}

// HotelCleared reports if the "hotel" edge to the Hotel entity was cleared.
func (m *ReservationMutation) HotelCleared() bool {
	return m.HotelIDCleared() || m.clearedhotel
}

// HotelIDs returns the "hotel" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// HotelID instead. It exists only for internal usage by the builders.
func (m *ReservationMutation) HotelIDs() (ids []int) {
	if id := m.hotel; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetHotel resets all changes to the "hotel" edge.
func (m *ReservationMutation) ResetHotel() {
	m.hotel = nil
	m.clearedhotel = false
}

// Where appends a list predicates to the ReservationMutation builder.
func (m *ReservationMutation) Where(ps ...predicate.Reservation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ReservationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ReservationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Reservation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ReservationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ReservationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Reservation).
func (m *ReservationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ReservationMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.reservation_uid != nil {
		fields = append(fields, reservation.FieldReservationUID)
	}
	if m.username != nil {
		fields = append(fields, reservation.FieldUsername)
	}
	if m.payment_uid != nil {
		fields = append(fields, reservation.FieldPaymentUID)
	}
	if m.hotel != nil {
		fields = append(fields, reservation.FieldHotelID)
	}
	if m.status != nil {
		fields = append(fields, reservation.FieldStatus)
	}
	if m.start_date != nil {
		fields = append(fields, reservation.FieldStartDate)
	}
	if m.end_date != nil {
		fields = append(fields, reservation.FieldEndDate)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ReservationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case reservation.FieldReservationUID:
		return m.ReservationUID()
	case reservation.FieldUsername:
		return m.Username()
	case reservation.FieldPaymentUID:
		return m.PaymentUID()
	case reservation.FieldHotelID:
		return m.HotelID()
	case reservation.FieldStatus:
		return m.Status()
	case reservation.FieldStartDate:
		return m.StartDate()
	case reservation.FieldEndDate:
		return m.EndDate()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ReservationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case reservation.FieldReservationUID:
		return m.OldReservationUID(ctx)
	case reservation.FieldUsername:
		return m.OldUsername(ctx)
	case reservation.FieldPaymentUID:
		return m.OldPaymentUID(ctx)
	case reservation.FieldHotelID:
		return m.OldHotelID(ctx)
	case reservation.FieldStatus:
		return m.OldStatus(ctx)
	case reservation.FieldStartDate:
		return m.OldStartDate(ctx)
	case reservation.FieldEndDate:
		return m.OldEndDate(ctx)
	}
	return nil, fmt.Errorf("unknown Reservation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReservationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case reservation.FieldReservationUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReservationUID(v)
		return nil
	case reservation.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case reservation.FieldPaymentUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPaymentUID(v)
		return nil
	case reservation.FieldHotelID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHotelID(v)
		return nil
	case reservation.FieldStatus:
		v, ok := value.(reservation.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case reservation.FieldStartDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartDate(v)
		return nil
	case reservation.FieldEndDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndDate(v)
		return nil
	}
	return fmt.Errorf("unknown Reservation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ReservationMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ReservationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReservationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Reservation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ReservationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(reservation.FieldHotelID) {
		fields = append(fields, reservation.FieldHotelID)
	}
	if m.FieldCleared(reservation.FieldStartDate) {
		fields = append(fields, reservation.FieldStartDate)
	}
	if m.FieldCleared(reservation.FieldEndDate) {
		fields = append(fields, reservation.FieldEndDate)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ReservationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ReservationMutation) ClearField(name string) error {
	switch name {
	case reservation.FieldHotelID:
		m.ClearHotelID()
		return nil
	case reservation.FieldStartDate:
		m.ClearStartDate()
		return nil
	case reservation.FieldEndDate:
		m.ClearEndDate()
		return nil
	}
	return fmt.Errorf("unknown Reservation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ReservationMutation) ResetField(name string) error {
	switch name {
	case reservation.FieldReservationUID:
		m.ResetReservationUID()
		return nil
	case reservation.FieldUsername:
		m.ResetUsername()
		return nil
	case reservation.FieldPaymentUID:
		m.ResetPaymentUID()
		return nil
	case reservation.FieldHotelID:
		m.ResetHotelID()
		return nil
	case reservation.FieldStatus:
		m.ResetStatus()
		return nil
	case reservation.FieldStartDate:
		m.ResetStartDate()
		return nil
	case reservation.FieldEndDate:
		m.ResetEndDate()
		return nil
	}
	return fmt.Errorf("unknown Reservation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ReservationMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.hotel != nil {
		edges = append(edges, reservation.EdgeHotel)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ReservationMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case reservation.EdgeHotel:
		if id := m.hotel; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ReservationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ReservationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ReservationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedhotel {
		edges = append(edges, reservation.EdgeHotel)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ReservationMutation) EdgeCleared(name string) bool {
	switch name {
	case reservation.EdgeHotel:
		return m.clearedhotel
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ReservationMutation) ClearEdge(name string) error {
	switch name {
	case reservation.EdgeHotel:
		m.ClearHotel()
		return nil
	}
	return fmt.Errorf("unknown Reservation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ReservationMutation) ResetEdge(name string) error {
	switch name {
	case reservation.EdgeHotel:
		m.ResetHotel()
		return nil
	}
	return fmt.Errorf("unknown Reservation edge %s", name)
}
