// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/predicate"
	"lab2/reservation/ent/reservation"
	"time"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReservationUpdate is the builder for updating Reservation entities.
type ReservationUpdate struct {
	config
	hooks    []Hook
	mutation *ReservationMutation
}

// Where appends a list predicates to the ReservationUpdate builder.
func (_u *ReservationUpdate) Where(ps ...predicate.Reservation) *ReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReservationUID sets the "reservation_uid" field.
func (_u *ReservationUpdate) SetReservationUID(v uuid.UUID) *ReservationUpdate {
	_u.mutation.SetReservationUID(v)
	return _u
}

// SetNillableReservationUID sets the "reservation_uid" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableReservationUID(v *uuid.UUID) *ReservationUpdate {
	if v != nil {
		_u.SetReservationUID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *ReservationUpdate) SetUsername(v string) *ReservationUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableUsername(v *string) *ReservationUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPaymentUID sets the "payment_uid" field.
func (_u *ReservationUpdate) SetPaymentUID(v uuid.UUID) *ReservationUpdate {
	_u.mutation.SetPaymentUID(v)
	return _u
}

// SetNillablePaymentUID sets the "payment_uid" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillablePaymentUID(v *uuid.UUID) *ReservationUpdate {
	if v != nil {
		_u.SetPaymentUID(*v)
	}
	return _u
}

// SetHotelID sets the "hotel_id" field.
func (_u *ReservationUpdate) SetHotelID(v int) *ReservationUpdate {
	_u.mutation.SetHotelID(v)
	return _u
}

// SetNillableHotelID sets the "hotel_id" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableHotelID(v *int) *ReservationUpdate {
	if v != nil {
		_u.SetHotelID(*v)
	}
	return _u
}

// ClearHotelID clears the value of the "hotel_id" field.
func (_u *ReservationUpdate) ClearHotelID() *ReservationUpdate {
	_u.mutation.ClearHotelID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReservationUpdate) SetStatus(v reservation.Status) *ReservationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableStatus(v *reservation.Status) *ReservationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ReservationUpdate) SetStartDate(v time.Time) *ReservationUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableStartDate(v *time.Time) *ReservationUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ReservationUpdate) ClearStartDate() *ReservationUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ReservationUpdate) SetEndDate(v time.Time) *ReservationUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ReservationUpdate) SetNillableEndDate(v *time.Time) *ReservationUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ReservationUpdate) ClearEndDate() *ReservationUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_u *ReservationUpdate) SetHotel(v *Hotel) *ReservationUpdate {
	return _u.SetHotelID(v.ID)
}

// Mutation returns the ReservationMutation object of the builder.
func (_u *ReservationUpdate) Mutation() *ReservationMutation {
	return _u.mutation
}

// ClearHotel clears the "hotel" edge to the Hotel entity.
func (_u *ReservationUpdate) ClearHotel() *ReservationUpdate {
	_u.mutation.ClearHotel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReservationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := reservation.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Reservation.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Reservation.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservation.Table, reservation.Columns, sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReservationUID(); ok {
		vv, err := reservation.ValueScanner.ReservationUID.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(reservation.FieldReservationUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(reservation.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentUID(); ok {
		vv, err := reservation.ValueScanner.PaymentUID.Value(value)
		if err != nil {
			return 0, err
		}
		_spec.SetField(reservation.FieldPaymentUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reservation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(reservation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(reservation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(reservation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(reservation.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.HotelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservation.HotelTable,
			Columns: []string{reservation.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservation.HotelTable,
			Columns: []string{reservation.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReservationUpdateOne is the builder for updating a single Reservation entity.
type ReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReservationMutation
}

// SetReservationUID sets the "reservation_uid" field.
func (_u *ReservationUpdateOne) SetReservationUID(v uuid.UUID) *ReservationUpdateOne {
	_u.mutation.SetReservationUID(v)
	return _u
}

// SetNillableReservationUID sets the "reservation_uid" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableReservationUID(v *uuid.UUID) *ReservationUpdateOne {
	if v != nil {
		_u.SetReservationUID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *ReservationUpdateOne) SetUsername(v string) *ReservationUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableUsername(v *string) *ReservationUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPaymentUID sets the "payment_uid" field.
func (_u *ReservationUpdateOne) SetPaymentUID(v uuid.UUID) *ReservationUpdateOne {
	_u.mutation.SetPaymentUID(v)
	return _u
}

// SetNillablePaymentUID sets the "payment_uid" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillablePaymentUID(v *uuid.UUID) *ReservationUpdateOne {
	if v != nil {
		_u.SetPaymentUID(*v)
	}
	return _u
}

// SetHotelID sets the "hotel_id" field.
func (_u *ReservationUpdateOne) SetHotelID(v int) *ReservationUpdateOne {
	_u.mutation.SetHotelID(v)
	return _u
}

// SetNillableHotelID sets the "hotel_id" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableHotelID(v *int) *ReservationUpdateOne {
	if v != nil {
		_u.SetHotelID(*v)
	}
	return _u
}

// ClearHotelID clears the value of the "hotel_id" field.
func (_u *ReservationUpdateOne) ClearHotelID() *ReservationUpdateOne {
	_u.mutation.ClearHotelID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReservationUpdateOne) SetStatus(v reservation.Status) *ReservationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableStatus(v *reservation.Status) *ReservationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ReservationUpdateOne) SetStartDate(v time.Time) *ReservationUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableStartDate(v *time.Time) *ReservationUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ReservationUpdateOne) ClearStartDate() *ReservationUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ReservationUpdateOne) SetEndDate(v time.Time) *ReservationUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ReservationUpdateOne) SetNillableEndDate(v *time.Time) *ReservationUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ReservationUpdateOne) ClearEndDate() *ReservationUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_u *ReservationUpdateOne) SetHotel(v *Hotel) *ReservationUpdateOne {
	return _u.SetHotelID(v.ID)
}

// Mutation returns the ReservationMutation object of the builder.
func (_u *ReservationUpdateOne) Mutation() *ReservationMutation {
	return _u.mutation
}

// ClearHotel clears the "hotel" edge to the Hotel entity.
func (_u *ReservationUpdateOne) ClearHotel() *ReservationUpdateOne {
	_u.mutation.ClearHotel()
	return _u
}

// Where appends a list predicates to the ReservationUpdate builder.
func (_u *ReservationUpdateOne) Where(ps ...predicate.Reservation) *ReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReservationUpdateOne) Select(field string, fields ...string) *ReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Reservation entity.
func (_u *ReservationUpdateOne) Save(ctx context.Context) (*Reservation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReservationUpdateOne) SaveX(ctx context.Context) *Reservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReservationUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := reservation.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Reservation.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Reservation.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReservationUpdateOne) sqlSave(ctx context.Context) (_node *Reservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reservation.Table, reservation.Columns, sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Reservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reservation.FieldID)
		for _, f := range fields {
			if !reservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReservationUID(); ok {
		vv, err := reservation.ValueScanner.ReservationUID.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(reservation.FieldReservationUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(reservation.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentUID(); ok {
		vv, err := reservation.ValueScanner.PaymentUID.Value(value)
		if err != nil {
			return nil, err
		}
		_spec.SetField(reservation.FieldPaymentUID, field.TypeString, vv)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reservation.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(reservation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(reservation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(reservation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(reservation.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.HotelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservation.HotelTable,
			Columns: []string{reservation.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservation.HotelTable,
			Columns: []string{reservation.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Reservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
