// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/reservation"
	"time"
	"uuid"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReservationCreate is the builder for creating a Reservation entity.
type ReservationCreate struct {
	config
	mutation *ReservationMutation
	hooks    []Hook
}

// SetReservationUID sets the "reservation_uid" field.
func (_c *ReservationCreate) SetReservationUID(v uuid.UUID) *ReservationCreate {
	_c.mutation.SetReservationUID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *ReservationCreate) SetUsername(v string) *ReservationCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPaymentUID sets the "payment_uid" field.
func (_c *ReservationCreate) SetPaymentUID(v uuid.UUID) *ReservationCreate {
	_c.mutation.SetPaymentUID(v)
	return _c
}

// SetHotelID sets the "hotel_id" field.
func (_c *ReservationCreate) SetHotelID(v int) *ReservationCreate {
	_c.mutation.SetHotelID(v)
	return _c
}

// SetNillableHotelID sets the "hotel_id" field if the given value is not nil.
func (_c *ReservationCreate) SetNillableHotelID(v *int) *ReservationCreate {
	if v != nil {
		_c.SetHotelID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReservationCreate) SetStatus(v reservation.Status) *ReservationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *ReservationCreate) SetStartDate(v time.Time) *ReservationCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *ReservationCreate) SetNillableStartDate(v *time.Time) *ReservationCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *ReservationCreate) SetEndDate(v time.Time) *ReservationCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *ReservationCreate) SetNillableEndDate(v *time.Time) *ReservationCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetHotel sets the "hotel" edge to the Hotel entity.
func (_c *ReservationCreate) SetHotel(v *Hotel) *ReservationCreate {
	return _c.SetHotelID(v.ID)
}

// Mutation returns the ReservationMutation object of the builder.
func (_c *ReservationCreate) Mutation() *ReservationMutation {
	return _c.mutation
}

// Save creates the Reservation in the database.
func (_c *ReservationCreate) Save(ctx context.Context) (*Reservation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReservationCreate) SaveX(ctx context.Context) *Reservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReservationCreate) check() error {
	if _, ok := _c.mutation.ReservationUID(); !ok {
		return &ValidationError{Name: "reservation_uid", err: errors.New(`ent: missing required field "Reservation.reservation_uid"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Reservation.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := reservation.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Reservation.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentUID(); !ok {
		return &ValidationError{Name: "payment_uid", err: errors.New(`ent: missing required field "Reservation.payment_uid"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Reservation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := reservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Reservation.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ReservationCreate) sqlSave(ctx context.Context) (*Reservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReservationCreate) createSpec() (*Reservation, *sqlgraph.CreateSpec, error) {
	var (
		_node = &Reservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reservation.Table, sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ReservationUID(); ok {
		vv, err := reservation.ValueScanner.ReservationUID.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(reservation.FieldReservationUID, field.TypeString, vv)
		_node.ReservationUID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(reservation.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PaymentUID(); ok {
		vv, err := reservation.ValueScanner.PaymentUID.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(reservation.FieldPaymentUID, field.TypeString, vv)
		_node.PaymentUID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(reservation.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(reservation.FieldStartDate, field.TypeTime, value)
		_node.StartDate = &value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(reservation.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if nodes := _c.mutation.HotelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reservation.HotelTable,
			Columns: []string{reservation.HotelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hotel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HotelID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// ReservationCreateBulk is the builder for creating many Reservation entities in bulk.
type ReservationCreateBulk struct {
	config
	err      error
	builders []*ReservationCreate
}

// Save creates the Reservation entities in the database.
func (_c *ReservationCreateBulk) Save(ctx context.Context) ([]*Reservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Reservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReservationCreateBulk) SaveX(ctx context.Context) []*Reservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
