// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/reservation"
	"strings"
	"time"
	"uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Reservation is the model entity for the Reservation schema.
type Reservation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ReservationUID holds the value of the "reservation_uid" field.
	ReservationUID uuid.UUID `json:"reservation_uid,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// PaymentUID holds the value of the "payment_uid" field.
	PaymentUID uuid.UUID `json:"payment_uid,omitempty"`
	// HotelID holds the value of the "hotel_id" field.
	HotelID *int `json:"hotel_id,omitempty"`
	// Status holds the value of the "status" field.
	Status reservation.Status `json:"status,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReservationQuery when eager-loading is set.
	Edges        ReservationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReservationEdges holds the relations/edges for other nodes in the graph.
type ReservationEdges struct {
	// Hotel holds the value of the hotel edge.
	Hotel *Hotel `json:"hotel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HotelOrErr returns the Hotel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReservationEdges) HotelOrErr() (*Hotel, error) {
	if e.Hotel != nil {
		return e.Hotel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hotel.Label}
	}
	return nil, &NotLoadedError{edge: "hotel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reservation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reservation.FieldID, reservation.FieldHotelID:
			values[i] = new(sql.NullInt64)
		case reservation.FieldUsername, reservation.FieldStatus:
			values[i] = new(sql.NullString)
		case reservation.FieldStartDate, reservation.FieldEndDate:
			values[i] = new(sql.NullTime)
		case reservation.FieldReservationUID:
			values[i] = reservation.ValueScanner.ReservationUID.ScanValue()
		case reservation.FieldPaymentUID:
			values[i] = reservation.ValueScanner.PaymentUID.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reservation fields.
func (_m *Reservation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reservation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case reservation.FieldReservationUID:
			if value, err := reservation.ValueScanner.ReservationUID.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.ReservationUID = value
			}
		case reservation.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case reservation.FieldPaymentUID:
			if value, err := reservation.ValueScanner.PaymentUID.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.PaymentUID = value
			}
		case reservation.FieldHotelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hotel_id", values[i])
			} else if value.Valid {
				_m.HotelID = new(int)
				*_m.HotelID = int(value.Int64)
			}
		case reservation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = reservation.Status(value.String)
			}
		case reservation.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case reservation.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reservation.
// This includes values selected through modifiers, order, etc.
func (_m *Reservation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHotel queries the "hotel" edge of the Reservation entity.
func (_m *Reservation) QueryHotel() *HotelQuery {
	return NewReservationClient(_m.config).QueryHotel(_m)
}

// Update returns a builder for updating this Reservation.
// Note that you need to call Reservation.Unwrap() before calling this method if this Reservation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Reservation) Update() *ReservationUpdateOne {
	return NewReservationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Reservation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Reservation) Unwrap() *Reservation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reservation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Reservation) String() string {
	var builder strings.Builder
	builder.WriteString("Reservation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reservation_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservationUID))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("payment_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentUID))
	builder.WriteString(", ")
	if v := _m.HotelID; v != nil {
		builder.WriteString("hotel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Reservations is a parsable slice of Reservation.
type Reservations []*Reservation
