// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lab2/reservation/ent/hotel"
	"lab2/reservation/ent/reservation"
	"lab2/reservation/ent/schema"
	"uuid"

	"entgo.io/ent/schema/field"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hotelFields := schema.Hotel{}.Fields()
	_ = hotelFields
	// hotelDescHotelUID is the schema descriptor for hotel_uid field.
	hotelDescHotelUID := hotelFields[0].Descriptor()
	hotel.ValueScanner.HotelUID = hotelDescHotelUID.ValueScanner.(field.TypeValueScanner[uuid.UUID])
	// hotelDescName is the schema descriptor for name field.
	hotelDescName := hotelFields[1].Descriptor()
	// hotel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	hotel.NameValidator = hotelDescName.Validators[0].(func(string) error)
	// hotelDescCountry is the schema descriptor for country field.
	hotelDescCountry := hotelFields[2].Descriptor()
	// hotel.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	hotel.CountryValidator = hotelDescCountry.Validators[0].(func(string) error)
	// hotelDescCity is the schema descriptor for city field.
	hotelDescCity := hotelFields[3].Descriptor()
	// hotel.CityValidator is a validator for the "city" field. It is called by the builders before save.
	hotel.CityValidator = hotelDescCity.Validators[0].(func(string) error)
	// hotelDescAddress is the schema descriptor for address field.
	hotelDescAddress := hotelFields[4].Descriptor()
	// hotel.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	hotel.AddressValidator = hotelDescAddress.Validators[0].(func(string) error)
	reservationFields := schema.Reservation{}.Fields()
	_ = reservationFields
	// reservationDescReservationUID is the schema descriptor for reservation_uid field.
	reservationDescReservationUID := reservationFields[0].Descriptor()
	reservation.ValueScanner.ReservationUID = reservationDescReservationUID.ValueScanner.(field.TypeValueScanner[uuid.UUID])
	// reservationDescUsername is the schema descriptor for username field.
	reservationDescUsername := reservationFields[1].Descriptor()
	// reservation.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	reservation.UsernameValidator = reservationDescUsername.Validators[0].(func(string) error)
	// reservationDescPaymentUID is the schema descriptor for payment_uid field.
	reservationDescPaymentUID := reservationFields[2].Descriptor()
	reservation.ValueScanner.PaymentUID = reservationDescPaymentUID.ValueScanner.(field.TypeValueScanner[uuid.UUID])
}
