// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// PaymentOrErr calls the predicate only if the error is not nit.
func PaymentOrErr(p Payment, err error) Payment {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
