// Code generated by ent, DO NOT EDIT.

package reservation

import (
	"fmt"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

const (
	// Label holds the string label denoting the reservation type in the database.
	Label = "reservation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReservationUID holds the string denoting the reservation_uid field in the database.
	FieldReservationUID = "reservation_uid"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPaymentUID holds the string denoting the payment_uid field in the database.
	FieldPaymentUID = "payment_uid"
	// FieldHotelID holds the string denoting the hotel_id field in the database.
	FieldHotelID = "hotel_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_data"
	// EdgeHotel holds the string denoting the hotel edge name in mutations.
	EdgeHotel = "hotel"
	// Table holds the table name of the reservation in the database.
	Table = "reservation"
	// HotelTable is the table that holds the hotel relation/edge.
	HotelTable = "reservation"
	// HotelInverseTable is the table name for the Hotel entity.
	// It exists in this package in order to avoid circular dependency with the "hotel" package.
	HotelInverseTable = "hotels"
	// HotelColumn is the table column denoting the hotel relation/edge.
	HotelColumn = "hotel_id"
)

// Columns holds all SQL columns for reservation fields.
var Columns = []string{
	FieldID,
	FieldReservationUID,
	FieldUsername,
	FieldPaymentUID,
	FieldHotelID,
	FieldStatus,
	FieldStartDate,
	FieldEndDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// ValueScanner of all Reservation fields.
	ValueScanner struct {
		ReservationUID field.TypeValueScanner[uuid.UUID]
		PaymentUID     field.TypeValueScanner[uuid.UUID]
	}
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusPAID     Status = "PAID"
	StatusCANCELED Status = "CANCELED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPAID, StatusCANCELED:
		return nil
	default:
		return fmt.Errorf("reservation: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Reservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReservationUID orders the results by the reservation_uid field.
func ByReservationUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationUID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPaymentUID orders the results by the payment_uid field.
func ByPaymentUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentUID, opts...).ToFunc()
}

// ByHotelID orders the results by the hotel_id field.
func ByHotelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHotelID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByHotelField orders the results by hotel field.
func ByHotelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHotelStep(), sql.OrderByField(field, opts...))
	}
}
func newHotelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HotelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HotelTable, HotelColumn),
	)
}
