// Code generated by ent, DO NOT EDIT.

package reservation

import (
	"fmt"
	"lab2/reservation/ent/predicate"
	"time"
	"uuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Reservation {
	return predicate.Reservation(sql.FieldLTE(FieldID, id))
}

// ReservationUID applies equality check predicate on the "reservation_uid" field. It's identical to ReservationUIDEQ.
func ReservationUID(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldEQ(FieldReservationUID, vc), err)
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldUsername, v))
}

// PaymentUID applies equality check predicate on the "payment_uid" field. It's identical to PaymentUIDEQ.
func PaymentUID(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldEQ(FieldPaymentUID, vc), err)
}

// HotelID applies equality check predicate on the "hotel_id" field. It's identical to HotelIDEQ.
func HotelID(v int) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldHotelID, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldEndDate, v))
}

// ReservationUIDEQ applies the EQ predicate on the "reservation_uid" field.
func ReservationUIDEQ(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldEQ(FieldReservationUID, vc), err)
}

// ReservationUIDNEQ applies the NEQ predicate on the "reservation_uid" field.
func ReservationUIDNEQ(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldNEQ(FieldReservationUID, vc), err)
}

// ReservationUIDIn applies the In predicate on the "reservation_uid" field.
func ReservationUIDIn(vs ...uuid.UUID) predicate.Reservation {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ReservationUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ReservationOrErr(sql.FieldIn(FieldReservationUID, v...), err)
}

// ReservationUIDNotIn applies the NotIn predicate on the "reservation_uid" field.
func ReservationUIDNotIn(vs ...uuid.UUID) predicate.Reservation {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ReservationUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ReservationOrErr(sql.FieldNotIn(FieldReservationUID, v...), err)
}

// ReservationUIDGT applies the GT predicate on the "reservation_uid" field.
func ReservationUIDGT(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldGT(FieldReservationUID, vc), err)
}

// ReservationUIDGTE applies the GTE predicate on the "reservation_uid" field.
func ReservationUIDGTE(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldGTE(FieldReservationUID, vc), err)
}

// ReservationUIDLT applies the LT predicate on the "reservation_uid" field.
func ReservationUIDLT(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldLT(FieldReservationUID, vc), err)
}

// ReservationUIDLTE applies the LTE predicate on the "reservation_uid" field.
func ReservationUIDLTE(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldLTE(FieldReservationUID, vc), err)
}

// ReservationUIDContains applies the Contains predicate on the "reservation_uid" field.
func ReservationUIDContains(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("reservation_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldContains(FieldReservationUID, vcs), err)
}

// ReservationUIDHasPrefix applies the HasPrefix predicate on the "reservation_uid" field.
func ReservationUIDHasPrefix(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("reservation_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldHasPrefix(FieldReservationUID, vcs), err)
}

// ReservationUIDHasSuffix applies the HasSuffix predicate on the "reservation_uid" field.
func ReservationUIDHasSuffix(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("reservation_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldHasSuffix(FieldReservationUID, vcs), err)
}

// ReservationUIDEqualFold applies the EqualFold predicate on the "reservation_uid" field.
func ReservationUIDEqualFold(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("reservation_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldEqualFold(FieldReservationUID, vcs), err)
}

// ReservationUIDContainsFold applies the ContainsFold predicate on the "reservation_uid" field.
func ReservationUIDContainsFold(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.ReservationUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("reservation_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldContainsFold(FieldReservationUID, vcs), err)
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Reservation {
	return predicate.Reservation(sql.FieldContainsFold(FieldUsername, v))
}

// PaymentUIDEQ applies the EQ predicate on the "payment_uid" field.
func PaymentUIDEQ(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldEQ(FieldPaymentUID, vc), err)
}

// PaymentUIDNEQ applies the NEQ predicate on the "payment_uid" field.
func PaymentUIDNEQ(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldNEQ(FieldPaymentUID, vc), err)
}

// PaymentUIDIn applies the In predicate on the "payment_uid" field.
func PaymentUIDIn(vs ...uuid.UUID) predicate.Reservation {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.PaymentUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ReservationOrErr(sql.FieldIn(FieldPaymentUID, v...), err)
}

// PaymentUIDNotIn applies the NotIn predicate on the "payment_uid" field.
func PaymentUIDNotIn(vs ...uuid.UUID) predicate.Reservation {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.PaymentUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.ReservationOrErr(sql.FieldNotIn(FieldPaymentUID, v...), err)
}

// PaymentUIDGT applies the GT predicate on the "payment_uid" field.
func PaymentUIDGT(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldGT(FieldPaymentUID, vc), err)
}

// PaymentUIDGTE applies the GTE predicate on the "payment_uid" field.
func PaymentUIDGTE(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldGTE(FieldPaymentUID, vc), err)
}

// PaymentUIDLT applies the LT predicate on the "payment_uid" field.
func PaymentUIDLT(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldLT(FieldPaymentUID, vc), err)
}

// PaymentUIDLTE applies the LTE predicate on the "payment_uid" field.
func PaymentUIDLTE(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.ReservationOrErr(sql.FieldLTE(FieldPaymentUID, vc), err)
}

// PaymentUIDContains applies the Contains predicate on the "payment_uid" field.
func PaymentUIDContains(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldContains(FieldPaymentUID, vcs), err)
}

// PaymentUIDHasPrefix applies the HasPrefix predicate on the "payment_uid" field.
func PaymentUIDHasPrefix(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldHasPrefix(FieldPaymentUID, vcs), err)
}

// PaymentUIDHasSuffix applies the HasSuffix predicate on the "payment_uid" field.
func PaymentUIDHasSuffix(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldHasSuffix(FieldPaymentUID, vcs), err)
}

// PaymentUIDEqualFold applies the EqualFold predicate on the "payment_uid" field.
func PaymentUIDEqualFold(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldEqualFold(FieldPaymentUID, vcs), err)
}

// PaymentUIDContainsFold applies the ContainsFold predicate on the "payment_uid" field.
func PaymentUIDContainsFold(v uuid.UUID) predicate.Reservation {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.ReservationOrErr(sql.FieldContainsFold(FieldPaymentUID, vcs), err)
}

// HotelIDEQ applies the EQ predicate on the "hotel_id" field.
func HotelIDEQ(v int) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldHotelID, v))
}

// HotelIDNEQ applies the NEQ predicate on the "hotel_id" field.
func HotelIDNEQ(v int) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldHotelID, v))
}

// HotelIDIn applies the In predicate on the "hotel_id" field.
func HotelIDIn(vs ...int) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldHotelID, vs...))
}

// HotelIDNotIn applies the NotIn predicate on the "hotel_id" field.
func HotelIDNotIn(vs ...int) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldHotelID, vs...))
}

// HotelIDIsNil applies the IsNil predicate on the "hotel_id" field.
func HotelIDIsNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldIsNull(FieldHotelID))
}

// HotelIDNotNil applies the NotNil predicate on the "hotel_id" field.
func HotelIDNotNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldNotNull(FieldHotelID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldStatus, vs...))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldNotNull(FieldStartDate))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.Reservation {
	return predicate.Reservation(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.Reservation {
	return predicate.Reservation(sql.FieldNotNull(FieldEndDate))
}

// HasHotel applies the HasEdge predicate on the "hotel" edge.
func HasHotel() predicate.Reservation {
	return predicate.Reservation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HotelTable, HotelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHotelWith applies the HasEdge predicate on the "hotel" edge with a given conditions (other predicates).
func HasHotelWith(preds ...predicate.Hotel) predicate.Reservation {
	return predicate.Reservation(func(s *sql.Selector) {
		step := newHotelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Reservation) predicate.Reservation {
	return predicate.Reservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Reservation) predicate.Reservation {
	return predicate.Reservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Reservation) predicate.Reservation {
	return predicate.Reservation(sql.NotPredicates(p))
}
