// Code generated by MockGen. DO NOT EDIT.
// Source: hotels.go
//
// Generated by this command:
//
//	mockgen -source=hotels.go -destination=../../core/usecases/hotels/repository_mock_test.go -package=hotels Hotels
//

// Package hotels is a generated GoMock package.
package hotels

import (
	context "context"
	entities "lab2/reservation/internal/models/entities"
	reflect "reflect"
	uuid "uuid"

	gomock "go.uber.org/mock/gomock"
)

// MockHotels is a mock of Hotels interface.
type MockHotels struct {
	ctrl     *gomock.Controller
	recorder *MockHotelsMockRecorder
	isgomock struct{}
}

// MockHotelsMockRecorder is the mock recorder for MockHotels.
type MockHotelsMockRecorder struct {
	mock *MockHotels
}

// NewMockHotels creates a new mock instance.
func NewMockHotels(ctrl *gomock.Controller) *MockHotels {
	mock := &MockHotels{ctrl: ctrl}
	mock.recorder = &MockHotelsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHotels) EXPECT() *MockHotelsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHotels) Get(arg0 context.Context, arg1 uuid.UUID) (entities.Hotel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(entities.Hotel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHotelsMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHotels)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockHotels) List(arg0 context.Context, arg1, arg2 int) (entities.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHotelsMockRecorder) List(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHotels)(nil).List), arg0, arg1, arg2)
}
