// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LoyaltyColumns holds the columns for the "loyalty" table.
	LoyaltyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 80},
		{Name: "reservation_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"BRONZE", "SILVER", "GOLD"}, Default: "BRONZE"},
		{Name: "discount", Type: field.TypeInt},
	}
	// LoyaltyTable holds the schema information for the "loyalty" table.
	LoyaltyTable = &schema.Table{
		Name:       "loyalty",
		Columns:    LoyaltyColumns,
		PrimaryKey: []*schema.Column{LoyaltyColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoyaltyTable,
	}
)

func init() {
	LoyaltyTable.Annotation = &entsql.Annotation{
		Table: "loyalty",
	}
}
