// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lab2/loyalty/ent/loyalty"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Loyalty is the model entity for the Loyalty schema.
type Loyalty struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// ReservationCount holds the value of the "reservation_count" field.
	ReservationCount int `json:"reservation_count,omitempty"`
	// Status holds the value of the "status" field.
	Status loyalty.Status `json:"status,omitempty"`
	// Discount holds the value of the "discount" field.
	Discount     int `json:"discount,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Loyalty) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loyalty.FieldID, loyalty.FieldReservationCount, loyalty.FieldDiscount:
			values[i] = new(sql.NullInt64)
		case loyalty.FieldUsername, loyalty.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Loyalty fields.
func (_m *Loyalty) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loyalty.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case loyalty.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case loyalty.FieldReservationCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_count", values[i])
			} else if value.Valid {
				_m.ReservationCount = int(value.Int64)
			}
		case loyalty.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = loyalty.Status(value.String)
			}
		case loyalty.FieldDiscount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field discount", values[i])
			} else if value.Valid {
				_m.Discount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Loyalty.
// This includes values selected through modifiers, order, etc.
func (_m *Loyalty) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Loyalty.
// Note that you need to call Loyalty.Unwrap() before calling this method if this Loyalty
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Loyalty) Update() *LoyaltyUpdateOne {
	return NewLoyaltyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Loyalty entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Loyalty) Unwrap() *Loyalty {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Loyalty is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Loyalty) String() string {
	var builder strings.Builder
	builder.WriteString("Loyalty(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("reservation_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservationCount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("discount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Discount))
	builder.WriteByte(')')
	return builder.String()
}

// Loyalties is a parsable slice of Loyalty.
type Loyalties []*Loyalty
