// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/loyalty/ent/loyalty"
	"lab2/loyalty/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoyaltyUpdate is the builder for updating Loyalty entities.
type LoyaltyUpdate struct {
	config
	hooks    []Hook
	mutation *LoyaltyMutation
}

// Where appends a list predicates to the LoyaltyUpdate builder.
func (_u *LoyaltyUpdate) Where(ps ...predicate.Loyalty) *LoyaltyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoyaltyUpdate) SetUsername(v string) *LoyaltyUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoyaltyUpdate) SetNillableUsername(v *string) *LoyaltyUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetReservationCount sets the "reservation_count" field.
func (_u *LoyaltyUpdate) SetReservationCount(v int) *LoyaltyUpdate {
	_u.mutation.ResetReservationCount()
	_u.mutation.SetReservationCount(v)
	return _u
}

// SetNillableReservationCount sets the "reservation_count" field if the given value is not nil.
func (_u *LoyaltyUpdate) SetNillableReservationCount(v *int) *LoyaltyUpdate {
	if v != nil {
		_u.SetReservationCount(*v)
	}
	return _u
}

// AddReservationCount adds value to the "reservation_count" field.
func (_u *LoyaltyUpdate) AddReservationCount(v int) *LoyaltyUpdate {
	_u.mutation.AddReservationCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LoyaltyUpdate) SetStatus(v loyalty.Status) *LoyaltyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LoyaltyUpdate) SetNillableStatus(v *loyalty.Status) *LoyaltyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *LoyaltyUpdate) SetDiscount(v int) *LoyaltyUpdate {
	_u.mutation.ResetDiscount()
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *LoyaltyUpdate) SetNillableDiscount(v *int) *LoyaltyUpdate {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// AddDiscount adds value to the "discount" field.
func (_u *LoyaltyUpdate) AddDiscount(v int) *LoyaltyUpdate {
	_u.mutation.AddDiscount(v)
	return _u
}

// Mutation returns the LoyaltyMutation object of the builder.
func (_u *LoyaltyUpdate) Mutation() *LoyaltyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoyaltyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoyaltyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoyaltyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoyaltyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoyaltyUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := loyalty.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Loyalty.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := loyalty.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Loyalty.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LoyaltyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loyalty.Table, loyalty.Columns, sqlgraph.NewFieldSpec(loyalty.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loyalty.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservationCount(); ok {
		_spec.SetField(loyalty.FieldReservationCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReservationCount(); ok {
		_spec.AddField(loyalty.FieldReservationCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(loyalty.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(loyalty.FieldDiscount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscount(); ok {
		_spec.AddField(loyalty.FieldDiscount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loyalty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoyaltyUpdateOne is the builder for updating a single Loyalty entity.
type LoyaltyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoyaltyMutation
}

// SetUsername sets the "username" field.
func (_u *LoyaltyUpdateOne) SetUsername(v string) *LoyaltyUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoyaltyUpdateOne) SetNillableUsername(v *string) *LoyaltyUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetReservationCount sets the "reservation_count" field.
func (_u *LoyaltyUpdateOne) SetReservationCount(v int) *LoyaltyUpdateOne {
	_u.mutation.ResetReservationCount()
	_u.mutation.SetReservationCount(v)
	return _u
}

// SetNillableReservationCount sets the "reservation_count" field if the given value is not nil.
func (_u *LoyaltyUpdateOne) SetNillableReservationCount(v *int) *LoyaltyUpdateOne {
	if v != nil {
		_u.SetReservationCount(*v)
	}
	return _u
}

// AddReservationCount adds value to the "reservation_count" field.
func (_u *LoyaltyUpdateOne) AddReservationCount(v int) *LoyaltyUpdateOne {
	_u.mutation.AddReservationCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LoyaltyUpdateOne) SetStatus(v loyalty.Status) *LoyaltyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LoyaltyUpdateOne) SetNillableStatus(v *loyalty.Status) *LoyaltyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *LoyaltyUpdateOne) SetDiscount(v int) *LoyaltyUpdateOne {
	_u.mutation.ResetDiscount()
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *LoyaltyUpdateOne) SetNillableDiscount(v *int) *LoyaltyUpdateOne {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// AddDiscount adds value to the "discount" field.
func (_u *LoyaltyUpdateOne) AddDiscount(v int) *LoyaltyUpdateOne {
	_u.mutation.AddDiscount(v)
	return _u
}

// Mutation returns the LoyaltyMutation object of the builder.
func (_u *LoyaltyUpdateOne) Mutation() *LoyaltyMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoyaltyUpdate builder.
func (_u *LoyaltyUpdateOne) Where(ps ...predicate.Loyalty) *LoyaltyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoyaltyUpdateOne) Select(field string, fields ...string) *LoyaltyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Loyalty entity.
func (_u *LoyaltyUpdateOne) Save(ctx context.Context) (*Loyalty, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoyaltyUpdateOne) SaveX(ctx context.Context) *Loyalty {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoyaltyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoyaltyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoyaltyUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := loyalty.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Loyalty.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := loyalty.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Loyalty.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LoyaltyUpdateOne) sqlSave(ctx context.Context) (_node *Loyalty, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loyalty.Table, loyalty.Columns, sqlgraph.NewFieldSpec(loyalty.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Loyalty.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loyalty.FieldID)
		for _, f := range fields {
			if !loyalty.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loyalty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loyalty.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservationCount(); ok {
		_spec.SetField(loyalty.FieldReservationCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReservationCount(); ok {
		_spec.AddField(loyalty.FieldReservationCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(loyalty.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(loyalty.FieldDiscount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscount(); ok {
		_spec.AddField(loyalty.FieldDiscount, field.TypeInt, value)
	}
	_node = &Loyalty{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loyalty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
