// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/loyalty/ent/loyalty"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoyaltyCreate is the builder for creating a Loyalty entity.
type LoyaltyCreate struct {
	config
	mutation *LoyaltyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsername sets the "username" field.
func (_c *LoyaltyCreate) SetUsername(v string) *LoyaltyCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetReservationCount sets the "reservation_count" field.
func (_c *LoyaltyCreate) SetReservationCount(v int) *LoyaltyCreate {
	_c.mutation.SetReservationCount(v)
	return _c
}

// SetNillableReservationCount sets the "reservation_count" field if the given value is not nil.
func (_c *LoyaltyCreate) SetNillableReservationCount(v *int) *LoyaltyCreate {
	if v != nil {
		_c.SetReservationCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LoyaltyCreate) SetStatus(v loyalty.Status) *LoyaltyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LoyaltyCreate) SetNillableStatus(v *loyalty.Status) *LoyaltyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDiscount sets the "discount" field.
func (_c *LoyaltyCreate) SetDiscount(v int) *LoyaltyCreate {
	_c.mutation.SetDiscount(v)
	return _c
}

// Mutation returns the LoyaltyMutation object of the builder.
func (_c *LoyaltyCreate) Mutation() *LoyaltyMutation {
	return _c.mutation
}

// Save creates the Loyalty in the database.
func (_c *LoyaltyCreate) Save(ctx context.Context) (*Loyalty, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoyaltyCreate) SaveX(ctx context.Context) *Loyalty {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoyaltyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoyaltyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoyaltyCreate) defaults() {
	if _, ok := _c.mutation.ReservationCount(); !ok {
		v := loyalty.DefaultReservationCount
		_c.mutation.SetReservationCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := loyalty.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoyaltyCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Loyalty.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := loyalty.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Loyalty.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReservationCount(); !ok {
		return &ValidationError{Name: "reservation_count", err: errors.New(`ent: missing required field "Loyalty.reservation_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Loyalty.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := loyalty.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Loyalty.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Discount(); !ok {
		return &ValidationError{Name: "discount", err: errors.New(`ent: missing required field "Loyalty.discount"`)}
	}
	return nil
}

func (_c *LoyaltyCreate) sqlSave(ctx context.Context) (*Loyalty, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoyaltyCreate) createSpec() (*Loyalty, *sqlgraph.CreateSpec) {
	var (
		_node = &Loyalty{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loyalty.Table, sqlgraph.NewFieldSpec(loyalty.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(loyalty.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.ReservationCount(); ok {
		_spec.SetField(loyalty.FieldReservationCount, field.TypeInt, value)
		_node.ReservationCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(loyalty.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Discount(); ok {
		_spec.SetField(loyalty.FieldDiscount, field.TypeInt, value)
		_node.Discount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Loyalty.Create().
//		SetUsername(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoyaltyUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *LoyaltyCreate) OnConflict(opts ...sql.ConflictOption) *LoyaltyUpsertOne {
	_c.conflict = opts
	return &LoyaltyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoyaltyCreate) OnConflictColumns(columns ...string) *LoyaltyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoyaltyUpsertOne{
		create: _c,
	}
}

type (
	// LoyaltyUpsertOne is the builder for "upsert"-ing
	//  one Loyalty node.
	LoyaltyUpsertOne struct {
		create *LoyaltyCreate
	}

	// LoyaltyUpsert is the "OnConflict" setter.
	LoyaltyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsername sets the "username" field.
func (u *LoyaltyUpsert) SetUsername(v string) *LoyaltyUpsert {
	u.Set(loyalty.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoyaltyUpsert) UpdateUsername() *LoyaltyUpsert {
	u.SetExcluded(loyalty.FieldUsername)
	return u
}

// SetReservationCount sets the "reservation_count" field.
func (u *LoyaltyUpsert) SetReservationCount(v int) *LoyaltyUpsert {
	u.Set(loyalty.FieldReservationCount, v)
	return u
}

// UpdateReservationCount sets the "reservation_count" field to the value that was provided on create.
func (u *LoyaltyUpsert) UpdateReservationCount() *LoyaltyUpsert {
	u.SetExcluded(loyalty.FieldReservationCount)
	return u
}

// AddReservationCount adds v to the "reservation_count" field.
func (u *LoyaltyUpsert) AddReservationCount(v int) *LoyaltyUpsert {
	u.Add(loyalty.FieldReservationCount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *LoyaltyUpsert) SetStatus(v loyalty.Status) *LoyaltyUpsert {
	u.Set(loyalty.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoyaltyUpsert) UpdateStatus() *LoyaltyUpsert {
	u.SetExcluded(loyalty.FieldStatus)
	return u
}

// SetDiscount sets the "discount" field.
func (u *LoyaltyUpsert) SetDiscount(v int) *LoyaltyUpsert {
	u.Set(loyalty.FieldDiscount, v)
	return u
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *LoyaltyUpsert) UpdateDiscount() *LoyaltyUpsert {
	u.SetExcluded(loyalty.FieldDiscount)
	return u
}

// AddDiscount adds v to the "discount" field.
func (u *LoyaltyUpsert) AddDiscount(v int) *LoyaltyUpsert {
	u.Add(loyalty.FieldDiscount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LoyaltyUpsertOne) UpdateNewValues() *LoyaltyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LoyaltyUpsertOne) Ignore() *LoyaltyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoyaltyUpsertOne) DoNothing() *LoyaltyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoyaltyCreate.OnConflict
// documentation for more info.
func (u *LoyaltyUpsertOne) Update(set func(*LoyaltyUpsert)) *LoyaltyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoyaltyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *LoyaltyUpsertOne) SetUsername(v string) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoyaltyUpsertOne) UpdateUsername() *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateUsername()
	})
}

// SetReservationCount sets the "reservation_count" field.
func (u *LoyaltyUpsertOne) SetReservationCount(v int) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetReservationCount(v)
	})
}

// AddReservationCount adds v to the "reservation_count" field.
func (u *LoyaltyUpsertOne) AddReservationCount(v int) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.AddReservationCount(v)
	})
}

// UpdateReservationCount sets the "reservation_count" field to the value that was provided on create.
func (u *LoyaltyUpsertOne) UpdateReservationCount() *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateReservationCount()
	})
}

// SetStatus sets the "status" field.
func (u *LoyaltyUpsertOne) SetStatus(v loyalty.Status) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoyaltyUpsertOne) UpdateStatus() *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateStatus()
	})
}

// SetDiscount sets the "discount" field.
func (u *LoyaltyUpsertOne) SetDiscount(v int) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *LoyaltyUpsertOne) AddDiscount(v int) *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *LoyaltyUpsertOne) UpdateDiscount() *LoyaltyUpsertOne {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateDiscount()
	})
}

// Exec executes the query.
func (u *LoyaltyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoyaltyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoyaltyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LoyaltyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LoyaltyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LoyaltyCreateBulk is the builder for creating many Loyalty entities in bulk.
type LoyaltyCreateBulk struct {
	config
	err      error
	builders []*LoyaltyCreate
	conflict []sql.ConflictOption
}

// Save creates the Loyalty entities in the database.
func (_c *LoyaltyCreateBulk) Save(ctx context.Context) ([]*Loyalty, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Loyalty, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoyaltyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoyaltyCreateBulk) SaveX(ctx context.Context) []*Loyalty {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoyaltyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoyaltyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Loyalty.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoyaltyUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *LoyaltyCreateBulk) OnConflict(opts ...sql.ConflictOption) *LoyaltyUpsertBulk {
	_c.conflict = opts
	return &LoyaltyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoyaltyCreateBulk) OnConflictColumns(columns ...string) *LoyaltyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoyaltyUpsertBulk{
		create: _c,
	}
}

// LoyaltyUpsertBulk is the builder for "upsert"-ing
// a bulk of Loyalty nodes.
type LoyaltyUpsertBulk struct {
	create *LoyaltyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LoyaltyUpsertBulk) UpdateNewValues() *LoyaltyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Loyalty.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LoyaltyUpsertBulk) Ignore() *LoyaltyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoyaltyUpsertBulk) DoNothing() *LoyaltyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoyaltyCreateBulk.OnConflict
// documentation for more info.
func (u *LoyaltyUpsertBulk) Update(set func(*LoyaltyUpsert)) *LoyaltyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoyaltyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *LoyaltyUpsertBulk) SetUsername(v string) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoyaltyUpsertBulk) UpdateUsername() *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateUsername()
	})
}

// SetReservationCount sets the "reservation_count" field.
func (u *LoyaltyUpsertBulk) SetReservationCount(v int) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetReservationCount(v)
	})
}

// AddReservationCount adds v to the "reservation_count" field.
func (u *LoyaltyUpsertBulk) AddReservationCount(v int) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.AddReservationCount(v)
	})
}

// UpdateReservationCount sets the "reservation_count" field to the value that was provided on create.
func (u *LoyaltyUpsertBulk) UpdateReservationCount() *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateReservationCount()
	})
}

// SetStatus sets the "status" field.
func (u *LoyaltyUpsertBulk) SetStatus(v loyalty.Status) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LoyaltyUpsertBulk) UpdateStatus() *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateStatus()
	})
}

// SetDiscount sets the "discount" field.
func (u *LoyaltyUpsertBulk) SetDiscount(v int) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *LoyaltyUpsertBulk) AddDiscount(v int) *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *LoyaltyUpsertBulk) UpdateDiscount() *LoyaltyUpsertBulk {
	return u.Update(func(s *LoyaltyUpsert) {
		s.UpdateDiscount()
	})
}

// Exec executes the query.
func (u *LoyaltyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LoyaltyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoyaltyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoyaltyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
