// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lab2/loyalty/ent/loyalty"
	"lab2/loyalty/ent/predicate"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeLoyalty = "Loyalty"
)

// LoyaltyMutation represents an operation that mutates the Loyalty nodes in the graph.
type LoyaltyMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	username             *string
	reservation_count    *int
	addreservation_count *int
	status               *loyalty.Status
	discount             *int
	adddiscount          *int
	clearedFields        map[string]struct{}
	done                 bool
	oldValue             func(context.Context) (*Loyalty, error)
	predicates           []predicate.Loyalty
}

var _ ent.Mutation = (*LoyaltyMutation)(nil)

// loyaltyOption allows management of the mutation configuration using functional options.
type loyaltyOption func(*LoyaltyMutation)

// newLoyaltyMutation creates new mutation for the Loyalty entity.
func newLoyaltyMutation(c config, op Op, opts ...loyaltyOption) *LoyaltyMutation {
	m := &LoyaltyMutation{
		config:        c,
		op:            op,
		typ:           TypeLoyalty,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLoyaltyID sets the ID field of the mutation.
func withLoyaltyID(id int) loyaltyOption {
	return func(m *LoyaltyMutation) {
		var (
			err   error
			once  sync.Once
			value *Loyalty
		)
		m.oldValue = func(ctx context.Context) (*Loyalty, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Loyalty.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLoyalty sets the old Loyalty of the mutation.
func withLoyalty(node *Loyalty) loyaltyOption {
	return func(m *LoyaltyMutation) {
		m.oldValue = func(context.Context) (*Loyalty, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LoyaltyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LoyaltyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LoyaltyMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LoyaltyMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Loyalty.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *LoyaltyMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *LoyaltyMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the Loyalty entity.
// If the Loyalty object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LoyaltyMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *LoyaltyMutation) ResetUsername() {
	m.username = nil
}

// SetReservationCount sets the "reservation_count" field.
func (m *LoyaltyMutation) SetReservationCount(i int) {
	m.reservation_count = &i
	m.addreservation_count = nil
}

// ReservationCount returns the value of the "reservation_count" field in the mutation.
func (m *LoyaltyMutation) ReservationCount() (r int, exists bool) {
	v := m.reservation_count
	if v == nil {
		return
	}
	return *v, true
}

// OldReservationCount returns the old "reservation_count" field's value of the Loyalty entity.
// If the Loyalty object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LoyaltyMutation) OldReservationCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReservationCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReservationCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReservationCount: %w", err)
	}
	return oldValue.ReservationCount, nil
}

// AddReservationCount adds i to the "reservation_count" field.
func (m *LoyaltyMutation) AddReservationCount(i int) {
	if m.addreservation_count != nil {
		*m.addreservation_count += i
	} else {
		m.addreservation_count = &i
	}
}

// AddedReservationCount returns the value that was added to the "reservation_count" field in this mutation.
func (m *LoyaltyMutation) AddedReservationCount() (r int, exists bool) {
	v := m.addreservation_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetReservationCount resets all changes to the "reservation_count" field.
func (m *LoyaltyMutation) ResetReservationCount() {
	m.reservation_count = nil
	m.addreservation_count = nil
}

// SetStatus sets the "status" field.
func (m *LoyaltyMutation) SetStatus(l loyalty.Status) {
	m.status = &l
}

// Status returns the value of the "status" field in the mutation.
func (m *LoyaltyMutation) Status() (r loyalty.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Loyalty entity.
// If the Loyalty object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LoyaltyMutation) OldStatus(ctx context.Context) (v loyalty.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *LoyaltyMutation) ResetStatus() {
	m.status = nil
}

// SetDiscount sets the "discount" field.
func (m *LoyaltyMutation) SetDiscount(i int) {
	m.discount = &i
	m.adddiscount = nil
}

// Discount returns the value of the "discount" field in the mutation.
func (m *LoyaltyMutation) Discount() (r int, exists bool) {
	v := m.discount
	if v == nil {
		return
	}
	return *v, true
}

// OldDiscount returns the old "discount" field's value of the Loyalty entity.
// If the Loyalty object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LoyaltyMutation) OldDiscount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDiscount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDiscount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDiscount: %w", err)
	}
	return oldValue.Discount, nil
}

// AddDiscount adds i to the "discount" field.
func (m *LoyaltyMutation) AddDiscount(i int) {
	if m.adddiscount != nil {
		*m.adddiscount += i
	} else {
		m.adddiscount = &i
	}
}

// AddedDiscount returns the value that was added to the "discount" field in this mutation.
func (m *LoyaltyMutation) AddedDiscount() (r int, exists bool) {
	v := m.adddiscount
	if v == nil {
		return
	}
	return *v, true
}

// ResetDiscount resets all changes to the "discount" field.
func (m *LoyaltyMutation) ResetDiscount() {
	m.discount = nil
	m.adddiscount = nil
}

// Where appends a list predicates to the LoyaltyMutation builder.
func (m *LoyaltyMutation) Where(ps ...predicate.Loyalty) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LoyaltyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LoyaltyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Loyalty, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LoyaltyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LoyaltyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Loyalty).
func (m *LoyaltyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LoyaltyMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.username != nil {
		fields = append(fields, loyalty.FieldUsername)
	}
	if m.reservation_count != nil {
		fields = append(fields, loyalty.FieldReservationCount)
	}
	if m.status != nil {
		fields = append(fields, loyalty.FieldStatus)
	}
	if m.discount != nil {
		fields = append(fields, loyalty.FieldDiscount)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LoyaltyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case loyalty.FieldUsername:
		return m.Username()
	case loyalty.FieldReservationCount:
		return m.ReservationCount()
	case loyalty.FieldStatus:
		return m.Status()
	case loyalty.FieldDiscount:
		return m.Discount()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LoyaltyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case loyalty.FieldUsername:
		return m.OldUsername(ctx)
	case loyalty.FieldReservationCount:
		return m.OldReservationCount(ctx)
	case loyalty.FieldStatus:
		return m.OldStatus(ctx)
	case loyalty.FieldDiscount:
		return m.OldDiscount(ctx)
	}
	return nil, fmt.Errorf("unknown Loyalty field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LoyaltyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case loyalty.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case loyalty.FieldReservationCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReservationCount(v)
		return nil
	case loyalty.FieldStatus:
		v, ok := value.(loyalty.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case loyalty.FieldDiscount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDiscount(v)
		return nil
	}
	return fmt.Errorf("unknown Loyalty field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LoyaltyMutation) AddedFields() []string {
	var fields []string
	if m.addreservation_count != nil {
		fields = append(fields, loyalty.FieldReservationCount)
	}
	if m.adddiscount != nil {
		fields = append(fields, loyalty.FieldDiscount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LoyaltyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case loyalty.FieldReservationCount:
		return m.AddedReservationCount()
	case loyalty.FieldDiscount:
		return m.AddedDiscount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LoyaltyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case loyalty.FieldReservationCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddReservationCount(v)
		return nil
	case loyalty.FieldDiscount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDiscount(v)
		return nil
	}
	return fmt.Errorf("unknown Loyalty numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LoyaltyMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LoyaltyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LoyaltyMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Loyalty nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LoyaltyMutation) ResetField(name string) error {
	switch name {
	case loyalty.FieldUsername:
		m.ResetUsername()
		return nil
	case loyalty.FieldReservationCount:
		m.ResetReservationCount()
		return nil
	case loyalty.FieldStatus:
		m.ResetStatus()
		return nil
	case loyalty.FieldDiscount:
		m.ResetDiscount()
		return nil
	}
	return fmt.Errorf("unknown Loyalty field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LoyaltyMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LoyaltyMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LoyaltyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LoyaltyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LoyaltyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LoyaltyMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LoyaltyMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Loyalty unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LoyaltyMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Loyalty edge %s", name)
}
