// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lab2/loyalty/ent/loyalty"
	"lab2/loyalty/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	loyaltyFields := schema.Loyalty{}.Fields()
	_ = loyaltyFields
	// loyaltyDescUsername is the schema descriptor for username field.
	loyaltyDescUsername := loyaltyFields[0].Descriptor()
	// loyalty.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	loyalty.UsernameValidator = loyaltyDescUsername.Validators[0].(func(string) error)
	// loyaltyDescReservationCount is the schema descriptor for reservation_count field.
	loyaltyDescReservationCount := loyaltyFields[1].Descriptor()
	// loyalty.DefaultReservationCount holds the default value on creation for the reservation_count field.
	loyalty.DefaultReservationCount = loyaltyDescReservationCount.Default.(int)
}
