// Code generated by ent, DO NOT EDIT.

package payment

import (
	"fmt"
	"lab2/payment/ent/predicate"
	"uuid"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldID, id))
}

// PaymentUID applies equality check predicate on the "payment_uid" field. It's identical to PaymentUIDEQ.
func PaymentUID(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldEQ(FieldPaymentUID, vc), err)
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldPrice, v))
}

// PaymentUIDEQ applies the EQ predicate on the "payment_uid" field.
func PaymentUIDEQ(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldEQ(FieldPaymentUID, vc), err)
}

// PaymentUIDNEQ applies the NEQ predicate on the "payment_uid" field.
func PaymentUIDNEQ(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldNEQ(FieldPaymentUID, vc), err)
}

// PaymentUIDIn applies the In predicate on the "payment_uid" field.
func PaymentUIDIn(vs ...uuid.UUID) predicate.Payment {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.PaymentUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.PaymentOrErr(sql.FieldIn(FieldPaymentUID, v...), err)
}

// PaymentUIDNotIn applies the NotIn predicate on the "payment_uid" field.
func PaymentUIDNotIn(vs ...uuid.UUID) predicate.Payment {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.PaymentUID.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.PaymentOrErr(sql.FieldNotIn(FieldPaymentUID, v...), err)
}

// PaymentUIDGT applies the GT predicate on the "payment_uid" field.
func PaymentUIDGT(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldGT(FieldPaymentUID, vc), err)
}

// PaymentUIDGTE applies the GTE predicate on the "payment_uid" field.
func PaymentUIDGTE(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldGTE(FieldPaymentUID, vc), err)
}

// PaymentUIDLT applies the LT predicate on the "payment_uid" field.
func PaymentUIDLT(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldLT(FieldPaymentUID, vc), err)
}

// PaymentUIDLTE applies the LTE predicate on the "payment_uid" field.
func PaymentUIDLTE(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	return predicate.PaymentOrErr(sql.FieldLTE(FieldPaymentUID, vc), err)
}

// PaymentUIDContains applies the Contains predicate on the "payment_uid" field.
func PaymentUIDContains(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.PaymentOrErr(sql.FieldContains(FieldPaymentUID, vcs), err)
}

// PaymentUIDHasPrefix applies the HasPrefix predicate on the "payment_uid" field.
func PaymentUIDHasPrefix(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.PaymentOrErr(sql.FieldHasPrefix(FieldPaymentUID, vcs), err)
}

// PaymentUIDHasSuffix applies the HasSuffix predicate on the "payment_uid" field.
func PaymentUIDHasSuffix(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.PaymentOrErr(sql.FieldHasSuffix(FieldPaymentUID, vcs), err)
}

// PaymentUIDEqualFold applies the EqualFold predicate on the "payment_uid" field.
func PaymentUIDEqualFold(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.PaymentOrErr(sql.FieldEqualFold(FieldPaymentUID, vcs), err)
}

// PaymentUIDContainsFold applies the ContainsFold predicate on the "payment_uid" field.
func PaymentUIDContainsFold(v uuid.UUID) predicate.Payment {
	vc, err := ValueScanner.PaymentUID.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("payment_uid value is not a string: %T", vc)
	}
	return predicate.PaymentOrErr(sql.FieldContainsFold(FieldPaymentUID, vcs), err)
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldStatus, vs...))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldPrice, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.NotPredicates(p))
}
