// Code generated by MockGen. DO NOT EDIT.
// Source: bookings.go
//
// Generated by this command:
//
//	mockgen -source=bookings.go -destination=../../core/usecases/bookings/repository_mock_test.go -package=bookings Bookings
//

// Package bookings is a generated GoMock package.
package bookings

import (
	context "context"
	entities "lab2/reservation/internal/models/entities"
	reflect "reflect"
	uuid "uuid"

	gomock "go.uber.org/mock/gomock"
)

// MockBookings is a mock of Bookings interface.
type MockBookings struct {
	ctrl     *gomock.Controller
	recorder *MockBookingsMockRecorder
	isgomock struct{}
}

// MockBookingsMockRecorder is the mock recorder for MockBookings.
type MockBookingsMockRecorder struct {
	mock *MockBookings
}

// NewMockBookings creates a new mock instance.
func NewMockBookings(ctrl *gomock.Controller) *MockBookings {
	mock := &MockBookings{ctrl: ctrl}
	mock.recorder = &MockBookingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookings) EXPECT() *MockBookingsMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockBookings) Cancel(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingsMockRecorder) Cancel(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookings)(nil).Cancel), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockBookings) Create(arg0 context.Context, arg1 entities.Booking) (entities.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(entities.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookingsMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookings)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockBookings) Get(arg0 context.Context, arg1 uuid.UUID, arg2 string) (entities.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBookingsMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBookings)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockBookings) List(arg0 context.Context, arg1 string) ([]entities.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]entities.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBookingsMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookings)(nil).List), arg0, arg1)
}
