// Code generated by ent, DO NOT EDIT.

package loyalty

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the loyalty type in the database.
	Label = "loyalty"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldReservationCount holds the string denoting the reservation_count field in the database.
	FieldReservationCount = "reservation_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDiscount holds the string denoting the discount field in the database.
	FieldDiscount = "discount"
	// Table holds the table name of the loyalty in the database.
	Table = "loyalty"
)

// Columns holds all SQL columns for loyalty fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldReservationCount,
	FieldStatus,
	FieldDiscount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultReservationCount holds the default value on creation for the "reservation_count" field.
	DefaultReservationCount int
)

// Status defines the type for the "status" enum field.
type Status string

// StatusBRONZE is the default value of the Status enum.
const DefaultStatus = StatusBRONZE

// Status values.
const (
	StatusBRONZE Status = "BRONZE"
	StatusSILVER Status = "SILVER"
	StatusGOLD   Status = "GOLD"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusBRONZE, StatusSILVER, StatusGOLD:
		return nil
	default:
		return fmt.Errorf("loyalty: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Loyalty queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByReservationCount orders the results by the reservation_count field.
func ByReservationCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDiscount orders the results by the discount field.
func ByDiscount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscount, opts...).ToFunc()
}
