// Code generated by ent, DO NOT EDIT.

package loyalty

import (
	"lab2/loyalty/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldUsername, v))
}

// ReservationCount applies equality check predicate on the "reservation_count" field. It's identical to ReservationCountEQ.
func ReservationCount(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldReservationCount, v))
}

// Discount applies equality check predicate on the "discount" field. It's identical to DiscountEQ.
func Discount(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldDiscount, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldContainsFold(FieldUsername, v))
}

// ReservationCountEQ applies the EQ predicate on the "reservation_count" field.
func ReservationCountEQ(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldReservationCount, v))
}

// ReservationCountNEQ applies the NEQ predicate on the "reservation_count" field.
func ReservationCountNEQ(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNEQ(FieldReservationCount, v))
}

// ReservationCountIn applies the In predicate on the "reservation_count" field.
func ReservationCountIn(vs ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldIn(FieldReservationCount, vs...))
}

// ReservationCountNotIn applies the NotIn predicate on the "reservation_count" field.
func ReservationCountNotIn(vs ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNotIn(FieldReservationCount, vs...))
}

// ReservationCountGT applies the GT predicate on the "reservation_count" field.
func ReservationCountGT(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGT(FieldReservationCount, v))
}

// ReservationCountGTE applies the GTE predicate on the "reservation_count" field.
func ReservationCountGTE(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGTE(FieldReservationCount, v))
}

// ReservationCountLT applies the LT predicate on the "reservation_count" field.
func ReservationCountLT(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLT(FieldReservationCount, v))
}

// ReservationCountLTE applies the LTE predicate on the "reservation_count" field.
func ReservationCountLTE(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLTE(FieldReservationCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNotIn(FieldStatus, vs...))
}

// DiscountEQ applies the EQ predicate on the "discount" field.
func DiscountEQ(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldEQ(FieldDiscount, v))
}

// DiscountNEQ applies the NEQ predicate on the "discount" field.
func DiscountNEQ(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNEQ(FieldDiscount, v))
}

// DiscountIn applies the In predicate on the "discount" field.
func DiscountIn(vs ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldIn(FieldDiscount, vs...))
}

// DiscountNotIn applies the NotIn predicate on the "discount" field.
func DiscountNotIn(vs ...int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldNotIn(FieldDiscount, vs...))
}

// DiscountGT applies the GT predicate on the "discount" field.
func DiscountGT(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGT(FieldDiscount, v))
}

// DiscountGTE applies the GTE predicate on the "discount" field.
func DiscountGTE(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldGTE(FieldDiscount, v))
}

// DiscountLT applies the LT predicate on the "discount" field.
func DiscountLT(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLT(FieldDiscount, v))
}

// DiscountLTE applies the LTE predicate on the "discount" field.
func DiscountLTE(v int) predicate.Loyalty {
	return predicate.Loyalty(sql.FieldLTE(FieldDiscount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Loyalty) predicate.Loyalty {
	return predicate.Loyalty(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Loyalty) predicate.Loyalty {
	return predicate.Loyalty(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Loyalty) predicate.Loyalty {
	return predicate.Loyalty(sql.NotPredicates(p))
}
